### ISSUE TITLE
Card 2 Astral Haze

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#10]
Card 2

Name: Astral Haze
Rarity: 0-Starter
Type: Skill
Basic [1 cost]: Ethereal. Gain 5 Block. The first time each enemy attacks you this turn, apply 2 Vulnerable and 2 Weak to it.
Upgrade [1 cost]: Ethereal. Gain 8 Block. The first time each enemy attacks you this turn, apply 3 Vulnerable and 3 Weak to it.

**Comment by gskleres** [comment]
No longer grants block. Now applies larger stacks.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Whoops - should be once per attacker, not once per individual attack. That was changed a bit back but I'm pretty sure I failed to communicate it properly, sorry! Updated the card text to reflect this.

**Comment by dvalldejuli** [comment]
Updated to apply effect to a particular attacker only once. Also updated effect so that it applies the debuff right after the triggered attack instead of after all queued actions.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Reworded: "Ethereal. The first time each enemy attacks you this turn, apply 2(3) Vulnerable and 2(3) Weak to it."

**Comment by gskleres** [comment]
BUG (COSMETIC): Text is butted up off the main card text area because of too many lines.

**Comment by daviscook477** [comment]
Works

**Comment by gskleres** [comment]
Now also gives 5(8) Block.
