### ISSUE TITLE
62 Chaos Form bug

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#112]
BUG: When combat ends, Chaos Form's effect does not end. You take it into the next combat. The effect should end when combat is over.

EDIT: This might actually only happen when you die while Chaos Form is active and start a new run.

NOTE: Chaos Form was changed to something else. The old Runic Binding took over for what Chaos Form used to be, so that's the card this bug fix will likely be applied to.

**Comment by daviscook477** [comment]
I believe you're right about it happening when dying with some powers active. I fixed it for Chaos Form and 4 other cards likely affected by the same issue.

**Comment by gskleres** [comment]
Seems to be fixed? I think we can close this for now.
