### ISSUE TITLE
Game crashes when fighting against Nemesis Elite

### ISSUE THREAD

**Issue by zsadan** [gskleres/FruityMod-StS#116]
## Expected Behavior
Game will not crash after ending the first turn.

## Actual Behavior

Game crashes after ending the first turn.

## Steps to Reproduce the Problem

  Relics: Arcanosphere, Neow's Lament Bronze Scales, Darkstone Periapt, Mango, Sozu, Ancient Tea Set, Calipers, Velvet Choker, Red Mask
   Stats: Life 87/89, 5 Energy, 3 Thorns
   Enemy: Attack 4x3, 175 life, 1 weak
  Hand content: Defend, Apotheosis, Event Horizon, Dimension Door, Strike+
  
1. Playing any or no card, and ending the turn will crash the game.

## Specifications

  - Version: latest
  - Platform: OSX
  - Subsystem:  java_version: 1.8.0_121 ; os_version: 10.13.3;  ModTheSpire 2.3.0

## Java Console content

Finding core patches...
Finding patches...
Injecting patches...Done.
Compiling patched classes...Done.
Patching enums...Done.
Setting isModded = true...Done.
Adding ModTheSpire to version...Done.
Initializing mods...
19:12:08.449 INFO basemod.BaseMod> initializeGson
19:12:08.469 INFO basemod.BaseMod> initializeTypeMaps
19:12:08.493 INFO fruitymod.FruityMod> ========================= FRUITYMOD INIT =========================
19:12:08.493 INFO fruitymod.FruityMod> subscribing to postInitialize event
19:12:08.494 INFO fruitymod.FruityMod> subscribing to editCharacters event
19:12:08.494 INFO fruitymod.FruityMod> subscribing to editRelics event
19:12:08.494 INFO fruitymod.FruityMod> subscribing to editCards event
19:12:08.495 INFO fruitymod.FruityMod> subscribing to editStrings event
19:12:08.495 INFO fruitymod.FruityMod> subscribing to onCardUse event
19:12:08.495 INFO fruitymod.FruityMod> creating the color PURPLE
19:12:08.496 INFO fruitymod.FruityMod> ================================================================
Done.
Starting game...
19:12:08.497 INFO desktop.DesktopLauncher> java_version: 1.8.0_121
19:12:08.497 INFO desktop.DesktopLauncher> os_arch: x86_64
19:12:08.497 INFO desktop.DesktopLauncher> os_name: Mac OS X
19:12:08.498 INFO desktop.DesktopLauncher> os_version: 10.13.3
19:12:08.498 INFO core.SystemStats> MEMORY STATS:
Free Memory: 171Mb
Max Memory: 3,641Mb
Allocated Memory: 364Mb
Unallocated Memory: 3,276Mb
Total Free Memory: 3,448Mb
Used Memory: 192Mb

19:12:08.500 INFO core.SystemStats> DISK STATS:
Total Space: 476,823Mb
Usable Space: 12,746Mb
Free Space: 18,524Mb

Mar 03, 2018 7:12:08 PM io.sentry.DefaultSentryClientFactory getInAppFrames
WARNING: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
Mar 03, 2018 7:12:08 PM io.sentry.DefaultSentryClientFactory getInAppFrames
WARNING: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
19:12:08.552 INFO core.DisplayConfig> Reading info.displayconfig
19:12:08.555 INFO core.DisplayConfig> DisplayConfig successfully read.
19:12:08.555 INFO desktop.DesktopLauncher> Settings successfully loaded
19:12:08.555 INFO desktop.DesktopLauncher> Launching application...
19:12:08.859 INFO core.CardCrawlGame> VERSION: 2018-03-01-PROD1
19:12:08.860 INFO core.CardCrawlGame> LIBGDX:  1.9.5
19:12:08.862 INFO ststwitch.TwitchConfig> The 'twitchconfig.txt' already exists, not overwriting it.
19:12:08.928 INFO steam.SteamSaveSync> [FAILURE] Steam API failed to initialize correctly.
No migration
19:12:08.936 INFO core.DisplayConfig> Reading info.displayconfig
19:12:08.937 INFO core.DisplayConfig> DisplayConfig successfully read.
19:12:08.943 INFO helpers.FileSaver> Save Succeeded: preferences/STSSound
19:12:08.946 INFO helpers.FileSaver> Save Succeeded: preferences/STSGameplaySettings
19:12:08.947 INFO helpers.FileSaver> Save Succeeded: preferences/STSGameplaySettings
19:12:08.986 INFO localization.LocalizedStrings> Loc Strings load time: 31ms
19:12:08.988 INFO basemod.BaseMod> begin editing localization strings
19:12:08.988 INFO fruitymod.FruityMod> begin editting strings
19:12:08.989 INFO basemod.BaseMod> loadJsonStrings: java.lang.Class
19:12:08.990 INFO basemod.BaseMod> loadJsonStrings: java.lang.Class
19:12:08.992 INFO fruitymod.FruityMod> done editting strings
19:12:09.103 INFO audio.MusicMaster> Music Volume: 0.5
19:12:09.106 INFO audio.SoundMaster> Sound Effect Volume: 0.5
19:12:09.107 INFO audio.SoundMaster> Loaded 289 Sound Effects
19:12:09.107 INFO audio.SoundMaster> SFX load time: 3ms
19:12:09.823 INFO cards.AbstractCard> Card Image load time: 710ms
19:12:10.780 INFO helpers.ImageMaster> Texture load time: 954ms
19:12:10.841 INFO helpers.FontHelper> Font load time (Map Fonts): 33ms
19:12:11.127 INFO helpers.FontHelper> Font load time (Kreon Standard): 285ms
19:12:11.519 INFO helpers.FontHelper> Font load time (The rest of it): 391ms
19:12:11.525 INFO unlock.UnlockTracker> RED UNLOCKS:   9/9
19:12:11.526 INFO unlock.UnlockTracker> GREEN UNLOCKS: 9/9
19:12:11.526 INFO unlock.UnlockTracker> RELIC UNLOCKS: 12/12
19:12:11.562 INFO unlock.UnlockTracker> CARDS SEEN:    264/0
19:12:11.584 INFO unlock.UnlockTracker> RELICS SEEN:   121/0
19:12:11.584 INFO basemod.BaseMod> publish post refresh - refreshing unlocks
19:12:11.585 INFO basemod.BaseMod> begin editing cards
19:12:11.585 INFO fruitymod.FruityMod> begin editting cards
19:12:11.586 INFO fruitymod.FruityMod> add cards for THE_SEEKER
19:12:11.813 INFO fruitymod.FruityMod> done editting cards
19:12:11.913 INFO panels.TopPanel> Twitch Integration enabled due to presence of 'twitch.properties` file.
19:12:11.914 INFO panels.TopPanel> Not starting twitch integration because enabled=false
incrementing card count for PURPLE to 0
incrementing card count for PURPLE to 1
incrementing card count for PURPLE to 2
incrementing card count for PURPLE to 3
incrementing card count for PURPLE to 4
incrementing card count for PURPLE to 5
incrementing card count for PURPLE to 6
incrementing card count for PURPLE to 7
incrementing card count for PURPLE to 8
incrementing card count for PURPLE to 9
incrementing card count for PURPLE to 10
incrementing card count for PURPLE to 11
incrementing card count for PURPLE to 12
incrementing card count for PURPLE to 13
incrementing card count for PURPLE to 14
incrementing card count for PURPLE to 15
incrementing card count for PURPLE to 16
incrementing card count for PURPLE to 17
incrementing card count for PURPLE to 18
incrementing card count for PURPLE to 19
incrementing card count for PURPLE to 20
incrementing card count for PURPLE to 21
incrementing card count for PURPLE to 22
incrementing card count for PURPLE to 23
incrementing card count for PURPLE to 24
incrementing card count for PURPLE to 25
incrementing card count for PURPLE to 26
incrementing card count for PURPLE to 27
incrementing card count for PURPLE to 28
incrementing card count for PURPLE to 29
incrementing card count for PURPLE to 30
incrementing card count for PURPLE to 31
incrementing card count for PURPLE to 32
incrementing card count for PURPLE to 33
incrementing card count for PURPLE to 34
incrementing card count for PURPLE to 35
incrementing card count for PURPLE to 36
incrementing card count for PURPLE to 37
incrementing card count for PURPLE to 38
incrementing card count for PURPLE to 39
incrementing card count for PURPLE to 40
incrementing card count for PURPLE to 41
incrementing card count for PURPLE to 42
incrementing card count for PURPLE to 43
incrementing card count for PURPLE to 44
incrementing card count for PURPLE to 45
incrementing card count for PURPLE to 46
incrementing card count for PURPLE to 47
incrementing card count for PURPLE to 48
incrementing card count for PURPLE to 49
incrementing card count for PURPLE to 50
incrementing card count for PURPLE to 51
incrementing card count for PURPLE to 52
incrementing card count for PURPLE to 53
incrementing card count for PURPLE to 54
incrementing card count for PURPLE to 55
incrementing card count for PURPLE to 56
incrementing card count for PURPLE to 57
incrementing card count for PURPLE to 58
incrementing card count for PURPLE to 59
incrementing card count for PURPLE to 60
incrementing card count for PURPLE to 61
incrementing card count for PURPLE to 62
incrementing card count for PURPLE to 63
incrementing card count for PURPLE to 64
incrementing card count for PURPLE to 65
incrementing card count for PURPLE to 66
incrementing card count for PURPLE to 67
incrementing card count for PURPLE to 68
incrementing card count for PURPLE to 69
incrementing card count for PURPLE to 70
incrementing card count for PURPLE to 71
incrementing card count for PURPLE to 72
incrementing card count for PURPLE to 73
19:12:12.176 INFO helpers.CardLibrary> Card load time: 363ms with 261 cards
19:12:12.176 INFO basemod.BaseMod> begin editing relics
19:12:12.177 INFO fruitymod.FruityMod> begin editting relics
19:12:12.184 INFO fruitymod.FruityMod> done editting relics
19:12:12.487 INFO helpers.RelicLibrary> Relic load time: 302ms
19:12:12.488 INFO helpers.InputHelper> Setting input processor to Scroller
19:12:12.514 INFO unlock.UnlockTracker> Retroactive Unlocks: 
19:12:12.515 INFO unlock.UnlockTracker> IRONCLAD unlock level: 6
19:12:12.519 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.519 INFO unlock.UnlockTracker> Hard Unlock: Blue Candle
19:12:12.521 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.522 INFO unlock.UnlockTracker> Hard Unlock: Dead Branch
19:12:12.525 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.525 INFO unlock.UnlockTracker> Hard Unlock: Singing Bowl
19:12:12.528 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.529 INFO unlock.UnlockTracker> Hard Unlock: Havoc
19:12:12.531 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.531 INFO unlock.UnlockTracker> Hard Unlock: Sentinel
19:12:12.534 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.535 INFO unlock.UnlockTracker> Hard Unlock: Exhume
19:12:12.537 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.537 INFO unlock.UnlockTracker> Hard Unlock: Wild Strike
19:12:12.539 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.540 INFO unlock.UnlockTracker> Hard Unlock: Evolve
19:12:12.542 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.543 INFO unlock.UnlockTracker> Hard Unlock: Immolate
19:12:12.545 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.545 INFO unlock.UnlockTracker> Hard Unlock: Omamori
19:12:12.547 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.547 INFO unlock.UnlockTracker> Hard Unlock: Prayer Wheel
19:12:12.549 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.549 INFO unlock.UnlockTracker> Hard Unlock: Shovel
19:12:12.551 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.551 INFO unlock.UnlockTracker> Hard Unlock: Heavy Blade
19:12:12.553 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.553 INFO unlock.UnlockTracker> Hard Unlock: Spot Weakness
19:12:12.555 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.555 INFO unlock.UnlockTracker> Hard Unlock: Limit Break
19:12:12.555 INFO unlock.UnlockTracker> THE_SILENT unlock level: 6
19:12:12.558 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.558 INFO unlock.UnlockTracker> Hard Unlock: Concentrate
19:12:12.559 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.560 INFO unlock.UnlockTracker> Hard Unlock: Setup
19:12:12.561 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.561 INFO unlock.UnlockTracker> Hard Unlock: Grand Finale
19:12:12.563 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.563 INFO unlock.UnlockTracker> Hard Unlock: Art of War
19:12:12.564 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.565 INFO unlock.UnlockTracker> Hard Unlock: The Courier
19:12:12.566 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.566 INFO unlock.UnlockTracker> Hard Unlock: Pandora's Box
19:12:12.568 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.569 INFO unlock.UnlockTracker> Hard Unlock: Cloak And Dagger
19:12:12.570 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.570 INFO unlock.UnlockTracker> Hard Unlock: Accuracy
19:12:12.572 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.572 INFO unlock.UnlockTracker> Hard Unlock: Storm of Steel
19:12:12.575 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.575 INFO unlock.UnlockTracker> Hard Unlock: Du-Vu Doll
19:12:12.577 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.577 INFO unlock.UnlockTracker> Hard Unlock: Smiling Mask
19:12:12.579 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.579 INFO unlock.UnlockTracker> Hard Unlock: Tiny Chest
19:12:12.582 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.582 INFO unlock.UnlockTracker> Hard Unlock: Bane
19:12:12.584 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.584 INFO unlock.UnlockTracker> Hard Unlock: Catalyst
19:12:12.586 INFO helpers.FileSaver> Save Succeeded: preferences/STSUnlocks
19:12:12.587 INFO unlock.UnlockTracker> Hard Unlock: Corpse Explosion
19:12:12.595 INFO basemod.BaseMod> publishPostInitialize
19:12:12.632 INFO basemod.BaseMod> registerModBadge : BaseMod
19:12:12.634 INFO basemod.ModBadge> initialized mod badge for: BaseMod
19:12:12.634 INFO basemod.ModBadge> setup hooks for BaseMod mod badge
19:12:12.634 INFO basemod.BaseMod> begin editing characters
19:12:12.635 INFO fruitymod.FruityMod> begin editting characters
19:12:12.635 INFO fruitymod.FruityMod> add THE_SEEKER
19:12:12.635 INFO fruitymod.FruityMod> done editting characters
19:12:12.708 INFO basemod.BaseMod> registerModBadge : FruityMod
19:12:12.708 INFO basemod.ModBadge> initialized mod badge for: FruityMod
19:12:12.709 INFO basemod.ModBadge> setup hooks for FruityMod mod badge
looking at prefs for IRONCLAD
looking at prefs for THE_SILENT
looking at prefs for CROWBOT
looking at prefs for THE_SEEKER
loading save for THE_SEEKER
looking at character THE_SEEKER with color PURPLE
19:12:17.587 INFO unlock.UnlockTracker> RED UNLOCKS:   9/9
19:12:17.587 INFO unlock.UnlockTracker> GREEN UNLOCKS: 9/9
19:12:17.587 INFO unlock.UnlockTracker> RELIC UNLOCKS: 12/12
19:12:17.587 INFO unlock.UnlockTracker> CARDS SEEN:    264/261
19:12:17.588 INFO unlock.UnlockTracker> RELICS SEEN:   121/118
19:12:17.588 INFO basemod.BaseMod> publish post refresh - refreshing unlocks
19:12:17.588 INFO mainMenu.CardLibraryScreen> Initializing card library screen.
215
289
19:12:17.596 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:17.600 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:17.601 INFO basemod.BaseMod> modifying character select screen
19:12:17.603 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:17.605 INFO basemod.BaseMod> adding option The Seeker
Fixing character select offsets
19:12:17.614 INFO saveAndContinue.SaveAndContinue> IRONCLAD save does NOT exist!
19:12:17.614 INFO saveAndContinue.SaveAndContinue> THE_SILENT save does NOT exist!
19:12:17.614 INFO saveAndContinue.SaveAndContinue> CROWBOT save does NOT exist!
checking if save exists
looing for saves/THE_SEEKER.autosave
19:12:17.644 INFO saveAndContinue.SaveAndContinue> saves/THE_SEEKER.autosave save file was successfully loaded.
19:12:17.688 INFO runHistory.RunHistoryScreen> Failed to load RunData from JSON file: runs/DAILY/1519999705.run
19:12:22.038 INFO basemod.BaseMod> hooking into character creation
19:12:22.039 INFO basemod.BaseMod> creating character THE_SEEKER
19:12:22.044 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.049 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.053 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.226 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.228 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.231 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.234 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.236 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.239 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.241 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.244 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.247 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.256 INFO saveAndContinue.SaveAndContinue> saves/THE_SEEKER.autosave save file was successfully loaded.
19:12:22.256 INFO core.CardCrawlGame> Strike_P, 1
19:12:22.257 INFO core.CardCrawlGame> Strike_P, 1
19:12:22.257 INFO core.CardCrawlGame> Strike_P, 0
19:12:22.258 INFO core.CardCrawlGame> Defend_P, 0
19:12:22.258 INFO core.CardCrawlGame> Defend_P, 0
19:12:22.258 INFO core.CardCrawlGame> Defend_P, 0
19:12:22.258 INFO core.CardCrawlGame> AstralHaze, 0
19:12:22.259 INFO core.CardCrawlGame> UmbralWave, 1
19:12:22.259 INFO core.CardCrawlGame> Flare, 0
19:12:22.259 INFO core.CardCrawlGame> EventHorizon, 0
19:12:22.260 INFO core.CardCrawlGame> UmbralWave, 1
19:12:22.260 INFO core.CardCrawlGame> Echo, 0
19:12:22.260 INFO core.CardCrawlGame> ArcaneBarrage, 1
19:12:22.261 INFO core.CardCrawlGame> AstralShift, 0
19:12:22.261 INFO core.CardCrawlGame> UmbralWave, 0
19:12:22.261 INFO core.CardCrawlGame> UmbralWave, 0
19:12:22.262 INFO core.CardCrawlGame> Corona, 0
19:12:22.262 INFO core.CardCrawlGame> Anomaly, 0
19:12:22.262 INFO core.CardCrawlGame> ArcaneVolley, 1
19:12:22.262 INFO core.CardCrawlGame> Enigma, 0
19:12:22.263 INFO core.CardCrawlGame> Apotheosis, 0
19:12:22.263 INFO core.CardCrawlGame> EventHorizon, 0
19:12:22.263 INFO core.CardCrawlGame> Madness, 0
19:12:22.264 INFO core.CardCrawlGame> Madness, 0
19:12:22.264 INFO core.CardCrawlGame> Flare, 1
19:12:22.266 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.268 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.271 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.273 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.274 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.276 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.278 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.280 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.283 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.285 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenRelics
19:12:22.287 INFO helpers.CardHelper> Obtained UmbralWave (COMMON). Creating new map entry.
19:12:22.292 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.293 INFO helpers.CardHelper> Obtained Flare (UNCOMMON). Creating new map entry.
19:12:22.296 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.296 INFO helpers.CardHelper> Obtained EventHorizon (UNCOMMON). Creating new map entry.
19:12:22.300 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.301 INFO helpers.CardHelper> Obtained UmbralWave (COMMON). You have 2 now
19:12:22.303 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.303 INFO helpers.CardHelper> Obtained Echo (RARE). Creating new map entry.
19:12:22.306 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.306 INFO helpers.CardHelper> Obtained ArcaneBarrage (COMMON). Creating new map entry.
19:12:22.309 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.310 INFO helpers.CardHelper> Obtained AstralShift (RARE). Creating new map entry.
19:12:22.313 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.313 INFO helpers.CardHelper> Obtained UmbralWave (COMMON). You have 3 now
19:12:22.316 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.316 INFO helpers.CardHelper> Obtained UmbralWave (COMMON). You have 4 now
19:12:22.319 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.319 INFO helpers.CardHelper> Obtained Corona (UNCOMMON). Creating new map entry.
19:12:22.323 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.323 INFO helpers.CardHelper> Obtained Anomaly (UNCOMMON). Creating new map entry.
19:12:22.326 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.326 INFO helpers.CardHelper> Obtained ArcaneVolley (COMMON). Creating new map entry.
19:12:22.329 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.329 INFO helpers.CardHelper> Obtained Enigma (RARE). Creating new map entry.
19:12:22.331 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.332 INFO helpers.CardHelper> Obtained Apotheosis (RARE). Creating new map entry.
19:12:22.334 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.335 INFO helpers.CardHelper> Obtained EventHorizon (UNCOMMON). You have 2 now
19:12:22.337 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.338 INFO helpers.CardHelper> Obtained Madness (UNCOMMON). Creating new map entry.
19:12:22.341 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.342 INFO helpers.CardHelper> Obtained Madness (UNCOMMON). You have 2 now
19:12:22.346 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.346 INFO helpers.CardHelper> Obtained Flare (UNCOMMON). You have 2 now
19:12:22.349 INFO helpers.FileSaver> Save Succeeded: preferences/STSSeenCards
19:12:22.350 INFO basemod.BaseMod> publishPreStartGame
19:12:22.433 INFO dungeons.AbstractDungeon> Loading seeds: 8953708643370720530
19:12:22.433 INFO dungeons.AbstractDungeon> Monster seed:  92
19:12:22.433 INFO dungeons.AbstractDungeon> Event seed:    26
19:12:22.433 INFO dungeons.AbstractDungeon> Merchant seed: 87
19:12:22.434 INFO dungeons.AbstractDungeon> Card seed:     530
19:12:22.434 INFO dungeons.AbstractDungeon> Treasure seed: 6
19:12:22.434 INFO dungeons.AbstractDungeon> Relic seed:    5
19:12:22.434 INFO dungeons.AbstractDungeon> Potion seed:   19
19:12:22.439 INFO dungeons.AbstractDungeon> [BOSS] Time Eater
19:12:22.496 INFO dungeons.AbstractDungeon> INIT CARD POOL
19:12:22.497 INFO dungeons.AbstractDungeon> COLORLESS CARDS: 24
19:12:22.497 INFO dungeons.AbstractDungeon> CURSE CARDS: 24
19:12:22.498 INFO dungeons.AbstractDungeon> Cardpool load time: 2ms
19:12:22.498 INFO dungeons.AbstractDungeon> Dungeon load time: 75ms
19:12:23.229 INFO scenes.AbstractScene> Fading in ambiance: AMBIANCE_BEYOND
19:12:23.558 INFO dungeons.AbstractDungeon> Generating Room Types! There are 53 rooms:
19:12:23.559 INFO dungeons.AbstractDungeon>  SHOP (5%): 3
19:12:23.560 INFO dungeons.AbstractDungeon>  REST (12%): 6
19:12:23.560 INFO dungeons.AbstractDungeon>  TRSRE (0%): 0
19:12:23.560 INFO dungeons.AbstractDungeon>  ELITE (8%): 4
19:12:23.560 INFO dungeons.AbstractDungeon>  EVNT (22%): 12
19:12:23.560 INFO dungeons.AbstractDungeon>  MSTR (53%): 28
19:12:23.568 INFO map.RoomTypeAssigner> #### Unassigned Rooms:
19:12:23.569 INFO map.RoomTypeAssigner> class com.megacrit.cardcrawl.rooms.MonsterRoom
19:12:23.570 INFO map.RoomTypeAssigner> class com.megacrit.cardcrawl.rooms.MonsterRoom
19:12:23.570 INFO map.RoomTypeAssigner> INFO: Node=(2,12):[(1,13), (2,13)] was null. Changed to a MonsterRoom.
19:12:23.570 INFO map.RoomTypeAssigner> INFO: Node=(2,13):[(2,14)] was null. Changed to a MonsterRoom.
19:12:23.570 INFO dungeons.AbstractDungeon> Generated the following dungeon map:
19:12:23.571 INFO dungeons.AbstractDungeon> 
           /  /   \  \     
14        R  R     R  R    
        /  / |   /    |    
13     M  M  M  M     M    
       |    \| \|     |    
12     M     M  M     M    
         \ / |/ |   /      
11        R  R  M  ?       
        /  /   \|/         
10     M  M     $          
       | \  \ /   \        
9      M  ?  R     E       
         \|/ |   / |       
8         T  T  T  T       
        / |/    |  |       
7      E  M     M  ?       
       |/ |     |/         
6      M  R     M          
       | \|   / |          
5      R  E  R  E          
       |/ |/      \        
4      ?  M        ?       
       | \| \        \     
3      ?  M  ?        ?    
       |/ | \  \      |    
2      ?  M  ?  $     ?    
       | \|  |/       |    
1      $  ?  M        M    
       |/  /            \  
0      M  M              M 
19:12:23.571 INFO dungeons.AbstractDungeon> Game Seed: 8953708643370720530
19:12:23.571 INFO dungeons.AbstractDungeon> Map generation time: 20ms
19:12:23.572 INFO dungeons.AbstractDungeon> Loading into: 0,7
19:12:23.572 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
19:12:24.854 INFO basemod.BaseMod> publishPostDraw
19:12:24.970 INFO basemod.BaseMod> publishPostDraw
19:12:25.086 INFO basemod.BaseMod> publishPostDraw
19:12:25.202 INFO basemod.BaseMod> publishPostDraw
19:12:25.303 INFO basemod.BaseMod> publishPostDraw
19:12:26.820 INFO audio.MusicMaster> Properly faded out MENU
19:12:30.271 INFO basemod.BaseMod> publish on card use
19:12:30.371 INFO basemod.BaseMod> publishPostExhaust
19:12:37.788 INFO basemod.BaseMod> publish on card use
19:12:38.655 INFO basemod.BaseMod> publish on card use
19:12:40.939 INFO basemod.BaseMod> publishPostExhaust
19:12:41.805 INFO basemod.BaseMod> publishPreMonsterTurn
19:12:41.806 INFO basemod.BaseMod> publishPreMonsterTurn
Exception: java.lang.ArrayIndexOutOfBoundsException: 2
19:12:41.808 ERROR core.CardCrawlGame> Exception caught
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.megacrit.cardcrawl.powers.IntangiblePower.updateDescription(IntangiblePower.java:57) ~[?:?]
	at com.megacrit.cardcrawl.powers.IntangiblePower.<init>(IntangiblePower.java:29) ~[?:?]
	at com.megacrit.cardcrawl.monsters.thebeyond.Nemesis.takeTurn(Nemesis.java:89) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.monsters.MonsterGroup.takeTurn(MonsterGroup.java:126) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:270) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:143) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:241) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2435) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:782) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:374) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Game closed.

**Comment by daviscook477** [comment]
Thanks for the report!

**Comment by zsadan** [comment]
I did not abandoned the run. 
If it helps I can submit / upload the game save if it is possible / useful.

**Comment by Lunaraia** [comment]
looks to be the same issue that BaseMod had with Nemesis' new Ethereal power, which automatically triggers on turn 2, might see if the fix there can be applied here as the error seems identical

**Comment by daviscook477** [comment]
I just tested with the latest release of BaseMod and it looks like this issue is fixed https://github.com/daviscook477/BaseMod/releases
