### ISSUE TITLE
Purple Skull does not work as intended

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#119]
Purple Skull does not work as intended, at the start of combat it will inflict -3 Dex on you since you don't have any status ailments

**Comment by daviscook477** [comment]
Oops

**Comment by daviscook477** [comment]
Fixed! Will be out in next patch.

**Comment by daviscook477** [comment]
The issue was that I wasn't resetting the state of purple skull in between combats so if you finished a combat with it active, the next combat would inflict negative dex
