### ISSUE TITLE
Relic Idea

### ISSUE THREAD

**Issue by daviscook477** [gskleres/FruityMod-StS#123]
oh I might have thought of one - Blueberries: When you add an Ethereal card to your deck, gain 1 max HP.
Haha! what do you think of that
either that or ... "Blueberries: Gain 1 max HP for each Ethereal card in your deck." so that it counts cards you already got.
fits the dumb fruit theme they have for max hp

by Fruistrike

**Comment by gskleres** [comment]
All Seeker relics consolidated here: #124
