### ISSUE TITLE
Seeker Relics

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#124]
Consolidating all the class Relics here in one issue for ease of perusal:

1. **Arcanosphere** (Starter): At the end of your turn, you may Top-Cycle 1 card.
2. **Paper Pengwin** (Uncommon): When you start a turn Frail, Weak, or Vulnerable, gain 1 Strength and 1 Dexterity until the end of turn.
3. **Solar Egg** (Uncommon): Whenever you add an Ethereal card to your deck, it is Upgraded.
4. **Rod of Negation** (Common): You may discard 1 card from your starting hand to gain 1 Artifact.
5. **Blueberries** (Uncommon): Gain 1 max HP for each Ethereal card in your deck.
6. **Telescope** (Rare): Choose any number of cards in your starting hand to gain Ethereal.
7. **Cosmic Sieve** (Boss): Whenever an Ethereal card enters your Exhaust Pile, gain 1 HP.

**Comment by daviscook477** [comment]
We have the tech necessary to change Aurora to "When you are Frail, Weak, or Vulnerable, gain 1 Strength and 1 Dexterity" so I think we should do that since it's more interesting that way.

**Comment by daviscook477** [comment]
Why **Solar Egg** instead of **Astral Egg**?

**Comment by gskleres** [comment]
Just trying to diversify the words for this class. I tried to not use a
word more than once (a couple exceptions - like Siphon Speed/Power - the
siphon part made sense to duplicate since the cards are mirrors of each
other). Feel free to change it back though! It's not a big deal at all. :)

**Comment by gskleres** [comment]
Renamed Aurora to Paper Pengwin to fit the slightly-misspelled paper animal that deals with status effects theme.

**Comment by gskleres** [comment]
Also increased the rarity of Paper Pengwin from Common to Uncommon, and decreased the rarity of Rod of Negation from Uncommon to Common.

**Comment by daviscook477** [comment]
Update Pawper Pengwin to "When you are Frail, Weak, or Vulnerable, gain 1 Strength and 1 Dexterity until the end of turn."

**Comment by gskleres** [comment]
Works!
