### ISSUE TITLE
Brainstorm is AWOL

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#126]
since I had been unable to find Brainstorm no matter how many runs I did, I just now broke down and used Basemod to get The Courier and about a million gold, having bought better part of 600 cards I have yet to get a single Brainstorm from the merchant, something is off here as Brainstorm is supposed to be an uncommon.

**Comment by daviscook477** [comment]
the latest version also re-enabled unlocks (I think?). I'm pretty sure Brainstorm is the first unlock. The game is probably bugging out with retroactive unlocks b/c I don't think I patched that code. If I had to guess...

**Comment by daviscook477** [comment]
Also we're really close to v0.2 release! :)

**Comment by Lunaraia** [comment]
neat! anyhow I can't test whether the exception is patched or not without actually being able to find Brainstorm as a card reward so until that line of code about retroactive unlocks gets fixed I cannot actually give a statement there, seeing as the crash happened when Brainstorm was a card reward.

**Comment by daviscook477** [comment]
so I don't think the crash was specific to card rewards. I used to base mod to force the 1st unlock level (which has Brainstorm) and then was able to see and purchase it in the shop without issue. So I think we're good. Probably.

**Comment by Lunaraia** [comment]
mind pointing the command to force unlocks my way so I can get the cards back as having checked the stats screen i am back to 0/9 unlocks and since i had already unlocked everything I am unable to get any of those cards legit
