### ISSUE TITLE
Seeker Card Unlocks

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#127]
Unlock Set 1: Self-Debuff theme
* Flicker
* Transference
* Force Ripple

Unlock Set 2: Ethereal theme
* Channel
* Shimmer
* Thought Raze

Unlock Set 3: Draw Trigger theme
* Convergence
* Hypothesis
* Nexus

**Comment by daviscook477** [comment]
Did you make changes in the code for this?

**Comment by gskleres** [comment]
I have not made any changes for this, just made this issue.

**Comment by Lunaraia** [comment]
please note that the unlock bug is still there and the card pool is now getting REALLY shallow as a result.

**Comment by gskleres** [comment]
@Lunaraia we are going to release v0.2 with everything unlocked - the unlocks will only be done for final release, however we're getting it tested now.

**Comment by Lunaraia** [comment]
that makes me happy because going through with seeker with only about 1/3 of the cards makes for redonk easy deck building since you are forced to take the same cards over and over

**Comment by gskleres** [comment]
@Lunaraia what do you mean by 1/3 of the cards? there should only be 9 cards out of the 75 total cards missing with unlocks

**Comment by Lunaraia** [comment]
I am still stuck without the cards from the old release cue and i cannot unlock them again (brainstorm ETC) not sure what broke it but I simply cannot get those cards anymore I had them unlocked but one of the earlier updates broke it,

The game treats me as having everything unlocked but keeps the unlock cards out of the pool, I tested this by spending nearly 300k Gold at the shop with The Courier and the unlock cards are not there for me

**Comment by gskleres** [comment]
@Lunaraia can you email me directly? george.skleres@gmail.com I'd like to chat with you on discord if possible?

**Comment by daviscook477** [comment]
Okay I'm going to do a fix that will create more work for the v1.0 release but it will fix everything for now. What I'll be doing is forcing an unlock on every seeker card. This will mean that we'll probably need to add a button to the options for fruitymod that is "reset unlocks" that people can use to play the v1.0 release if they've played pre-v1.0

**Comment by gskleres** [comment]
That seems reasonable. I wonder how MegaCrit does it?

**Comment by Lunaraia** [comment]
probably have a check written into the cards themselves? something along the lines of UnlockCard=True or something of that sort, maybe?

**Comment by daviscook477** [comment]
They have some methods for handling things reotroactively so we could look at those for inspiration

**Comment by gskleres** [comment]
CLosing for now
