### ISSUE TITLE
Card 4 Irradiate

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#13]
Card 4

Name: Irradiate
Rarity: 1-Common
Type: Attack
Basic [1 cost]: Deal 1 damage and apply 1 Weak and 1 Vulnerable to ALL enemies.
Upgrade [1 cost]: Deal 2 damage and apply 2 Weak and 2 Vulnerable to ALL enemies.

**Comment by gskleres** [comment]
Works!

**Comment by daviscook477** [comment]
Arcane Volley

**Comment by gskleres** [comment]
Class file needs name/references to "ArcaneVolley" updated to "Irradiate"

**Comment by gskleres** [comment]
Now applies 1(2) of both Weak and Vulnerable. Damage decreased from 8(10) to 3(5). Cost decreased from 2(2) to 1(1).

**Comment by gskleres** [comment]
BUG (COSMETIC): There is no number before the word Vulnerable.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Damage reduced from 3(5) to 1(2).
