### ISSUE TITLE
Nebula displays incorrect block amount until selected when using Power Cells relic

### ISSUE THREAD

**Issue by kiooeht** [gskleres/FruityMod-StS#131]
## Expected Behavior
When you have the Power Cells relic, your starting hand is all Ethereal. Nebula should display block equal to your hand size times the block amount.

## Actual Behavior
Nebula only displays block equal to the number of cards that were originally Ethereal times the block amount.

![image](https://user-images.githubusercontent.com/236842/37019056-97c602f6-20cb-11e8-8da1-3300fbea2a57.png)
![image](https://user-images.githubusercontent.com/236842/37019073-a297a554-20cb-11e8-985d-5c9ca43169d9.png)

Selecting the card corrects the block gain.

![image](https://user-images.githubusercontent.com/236842/37019505-53d2a098-20cd-11e8-87ee-3194e159824f.png)

## Steps to Reproduce the Problem

  1. Have Power Cells relic.
  1. Get Nebula in starting hand.
  1. Nebula displays incorrect block gain.
  1. Click on Nebula.
  1. Nebula now displays correct block gain.

**Comment by daviscook477** [comment]
I'm going to guess this one is some issue with how I set up the EtherealizeAction that is used by Power Cells. Thanks for the heads up. Nebula updates it's block amount when powers are applied so since Power Cells uses an action I'm guessing that's what's going wrong.

**Comment by daviscook477** [comment]
I wonder if this also applies to Shimmer? I'm pretty sure it doesn't.
