### ISSUE TITLE
Power Cells + Nexus

### ISSUE THREAD

**Issue by kiooeht** [gskleres/FruityMod-StS#132]
## Expected Behavior
Non-Ethereal cards made Ethereal by Power Cells relic should not be duplicated by Nexus power.

## Actual Behavior
New Ethereal copies of cards are made by Nexus when drawing cards that were made Ethereal by Power Cells.

## Steps to Reproduce the Problem

  1. Have Power Cells relic.
  1. Have non-Ethereal card in starting hand, it becomes Ethereal.
  1. Play Nexus.
  1. Draw said card from step 2 later.

**Comment by daviscook477** [comment]
Well that's unique. I'll try and figure that out.

**Comment by daviscook477** [comment]
Fixed in latest release.
