### ISSUE TITLE
Blueberries Change

### ISSUE THREAD

**Issue by daviscook477** [gskleres/FruityMod-StS#137]
Change relic text to "Gain max HP equal to the number of ethereal cards in your deck. When you add an ethereal card to your deck gain 1 max HP. When you remove an ethereal card from your deck lose 1 max HP." and make the appropriate changes to functionality.

Right now it can be kinda underwhelming if you get it too early and the wording is ambiguous.

**Comment by gskleres** [comment]
Actually don't do the above. The relic is fine as is. :)
