### ISSUE TITLE
Card 5 Essence Dart

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#14]
Card 5

Name: Essence Dart
Rarity: 1-Common
Type: Attack
Basic [0 cost]: Can only be played if you have an Ethereal card in your hand. Deal 11 damage.
Upgrade [0 cost]: Can only be played if you have an Ethereal card in your hand. Deal 15 damage.

**Comment by gskleres** [comment]
Works!

**Comment by daviscook477** [comment]
Changed name from Ether Bolt to Essence Dart

**Comment by gskleres** [comment]
Class name/references need updating from "EtherBolt" to "EssenceDart"

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
DESIGN UPDATE: Now works if you have at least 1 Ethereal card in hand, not only if you have ALL ethereal cards. Damage reduced to 12(16).

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (cosmetic): Currently has the same art as Phase Coil.

**Comment by gskleres** [comment]
Cost reduced from 1(1) to 0(0). Damage reduced from 12(16) to 11(15).

**Comment by gskleres** [comment]
Works!
