### ISSUE TITLE
Card 6 Null Storm

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#15]
Card 6

Name: Null Storm
Rarity: 1-Common
Type: Attack
Basic [1 cost]: Shuffle a Dazed into your draw pile. Deal 8 damage to ALL enemies.
Upgrade [1 cost]: Shuffle a Dazed into your draw pile. Deal 11 damage to ALL enemies.

**Comment by gskleres** [comment]
Rarity updated to Uncommon.

**Comment by gskleres** [comment]
Works!

**Comment by daviscook477** [comment]
Changed name from Flux Blast to Null Storm

**Comment by gskleres** [comment]
Class name/references need updating from "FluxBlast" to "NullStorm"

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic): Rename in game name to Null Storm.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Rarity decreased from Uncommon to Common.

**Comment by gskleres** [comment]
Works!
