### ISSUE TITLE
Ascension Mode bugged

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#152]
When finishing a level of Ascension, the next level does not unlock. Should unlock just like Ironclad and Silent do.

**Comment by daviscook477** [comment]
Ascension mode hasn't even been looked at yet. I doubt it's even working correctly

**Comment by Lunaraia** [comment]
Ascension levels are all unlocked for me I just have to move it up from 0 every time I start a new run

**Comment by gskleres** [comment]
@daviscook477 how much work will it be to enable ascension mode?
