### ISSUE TITLE
Seeker model too big

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#153]
The seeker's model is way too big. Should be somewhere between 1/2 to 2/3 of the current size. Here is an image to help:

![hugeseeker](https://user-images.githubusercontent.com/11493238/37216244-59b54688-2388-11e8-9502-b203a565866c.png)

**Comment by Lunaraia** [comment]
who says that The Seeker has to be human? could be some form of benign eldritch entity behind that mask :P

**Comment by gskleres** [comment]
Implemented.
