### ISSUE TITLE
Comet + Exhausted pile bug

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#156]
Comet is currently gaining damage boost from ethereal cards in the exhaust pile. This should not be the case (that's for Dark Matter). Comet should only gain a damage boost from Ethereal cards in your draw pile, your hand, and your discard pile.

**Comment by daviscook477** [comment]
Not a bug. Expected behavior

**Comment by gskleres** [comment]
@daviscook477 it's definitely a bug - Perfected Strike does not do this and has the exact same wording.

**Comment by fiiiiilth** [comment]
Yeah, I must've mixed them up at some point and told you the wrong thing, My bad.

**Comment by gskleres** [comment]
Works!
