### ISSUE TITLE
Card 7 Void Ray

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#16]
Card 7

Name: Void Ray
Rarity: 1-Common
Type: Attack
Basic [1 cost]: Shuffle a Dazed into your draw pile. Deal 10 damage.
Upgrade [1 cost]: Shuffle a Dazed into your draw pile. Deal 14 damage.

**Comment by gskleres** [comment]
Damage decreased from 10(14) to 10(13).

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic): Rename in game name to Void Ray.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Damage increased from 10(13) to 10(14).

**Comment by gskleres** [comment]
Works!
