### ISSUE TITLE
Echo+ and Daze Crash

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#162]
I were toying around with The Seeker and having a jolly good time, however when I played a Daze after using Echo the game instantly crashed on me, I would have posted an error message about it, but this was using the Custom daily climb mod that Davis made so I don't have a save file for it that I can test from and with the newest version of ModtheSpire the console closes automatically after the game starts so I couldn't pull any error messages from it.

**Comment by daviscook477** [comment]
If you want ModTheSpire to not automatically close after the game ends you just need to put it in debug mode now. I'll take a look at the Echo + Daze bug soon.

**Comment by gskleres** [comment]
This *might* be solved by the new Enigma, which transforms Dazed into a separate attack card #73 still needs double checking...

**Comment by gskleres** [comment]
Resolved by implementing new Enigma #73
