### ISSUE TITLE
Daze does not scale with Voulnerable and Slow and Power Overwhelming bug

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#163]
## Expected Behavior
Since Daze are now turned into attacks they should be affected by Vulnerable and Slow

## Actual Behavior

They are not affected by Vulnerable and Slow
## Steps to Reproduce the Problem

 1. Play Enigma, Power Overwhelming and Brilliance while having Mummified Hand, Marbles and Unceasing Top as relics
  
 2. Play the resulting daze that you will draw if those are the only cards in your deck

 3. Notice that the Daze' will still only deal 8 damage vs Vulnerable enemies, despite it advertising greater damage, this becomes VERY noticeable against the Statue Head Elite in Act 3.

 4. You will also get 2 Daze' shuffled into your deck even though you are supposed to only get one when playing Daze that has been turned into an attack with Enigma. Suspect this is related to Daze normally being a Status.

## Specifications

All the newest updated stuff in terms of Mods.

**Comment by gskleres** [comment]
This is solved by the new Enigma, which transforms Dazed into a separate attack card #73
