### ISSUE TITLE
Card Summary - Play Testing

### ISSUE THREAD

**Issue by Meow-Mixer** [gskleres/FruityMod-StS#165]
Astral Haze (C)(1) - Cost prohibitive, it generally gets in the way of more defense, or a faster kill.
Arcane Armor (C)(2) - Works well in smaller decks during drawn out fights.
Channel (C)(1) - Works well as is.
Convergence (C)(-) - Only works with top cycling, like a drastically weaker armaments.
Disruption Field (C)(1) - Works well as is.
Essence Dart (C)(0) - Works well as is.
Ether Blast (C)(0) - Work well as is.
Flicker (C)(1) - Current version unplayable, newest version seems like a good alternative.
Flux (C)(1) - Works well as is.
Genesis (C)(1) - Works well as is.
Irradiate (C)(1) - Works well as is, love this card.
Magic Missile (C)(1) - Works well, but i'd like to see it lose exhaust in some form, instead of being a pummel copy.
Nebula (C)(1) - Works well as is.
Null Storm (C)(1) - Works well enough, newest version seems like a good alternative.
Phase Coil (C)(4) - Works well as is.
Prismatic Sphere (C)(1) - Works well as is.
Pulse Barrier (C)(1) - Never taken as card choice, due to current meta.
Retrograde (C)(0) - Interesting card, tough to finish high health fights before the card bloat gets you.
Surge (C)(1) - Works well enough.
Unstable Orb (C)(1) - Never taken as card choice, due to current meta.
Void ray (C)(1) - Seems like a much weaker Null Storm.

Anomaly (U)(1) - Works well as is.
Archives (U)(0) - Works severely poor unless in librarian-esque decks, or with intentional card bloat.
Brainstorm (U)(0) - Works well as is.
Coalescence (U)(1) - Nearly useless in current meta.
Comet (U)(1) - Works well before daze bloat due to enigma, then overpowering.
Corona (U)(1) - Works well as is.
Creativity (U)(1) - Works well as is.
Dark Matter (U)(1) - Works well, except in conjunction with Enigma.
Disperse (U)(2) - Works well, a must choose defensive card.
Enigma (U)(1) - Wonderful concept, fairly weak as is, except with the more obvious card combos.
Entropy (U)(1) - Nice concept, but fairly weak for a temporary benefit.
Equinox (U)(1) - Nice concept, not often chosen.
Event Horizon (U)(1) - Works well, big fan of it's synergy with Astral Haze, Irradiate, and Anomaly.
Flare (U)(1) - Nice concept, feels like a poor mans Thunderclap.
Flow (U)(1) - Works well enough as is.
Gravity Well (U)(1) - Seems like a weaker disarm due to conditional interaction.
Hypothesis (U)(1) - Works well as is, would be neat if it chained itself.
Illuminate (U)(0) - Works well enough, not a fan of the top cycle portion.
Magnetize (U)(0) - Severely under powered until upgrade, then works well.
Nova (U)(3) - Works well, seems like too many daze after Null Storm update.
Overload (U)(0) - Currently very dangerous to use, newest update seems fine.
Plasma Wave (U)(X) - Feels like a weaker whirlwind.
Shimmer (U)(1) - Works well enough, would prefer it lost exhaust instead of increased armor on upgrade.
Singularity (U)(3) - Overly expensive, would like to see reduced cost on upgrade.
Siphon Power (U)(2) - Works well as is, wouldn't mind increased stat on upgrade.
Siphon Speed (U)(2) - Works well as is, wouldn't mind increased stat on upgrade.
Starburst (U)(2) - Works well as is, fun to use with strength meta.
Stroke of Genius (U)(1) - Works well as is.
Syzygy (U)(1) - Feels like a much worse magic missile.
Transference (U)(1) - Works well enough as is.
Umbra (U)(1) - Unplayable without Brilliance
Vacuum (U)(2) - Feels like too high a cost for the conditional employment.
Vortex (U)(1) - Fun concept, too easily abuse-able with Enigma and/or Brilliance.
Wormhole (U)(3) - Cost prohibitive, just as unplayable as its' Silent counterpart.

Brilliance (R)(2) - Works well as is.
Chaos Form (R)(3) - Fun concept, currently cost prohibitive.
Dimension Door (R)(3) - Fun concept, currently cost prohibitive
Echo (R)(1) - Works well as is.
Eclipse (R)(1) - Too many conditional statements for current cost, especially for its rarity.
Eureka (R)(0) - Works well as is.
Feedback (R)(1) - Works well as is, at current rarity.
Force Ripple (R)(1) - Unplayable in current meta, except as killing blow.
Implosion (R)(3) - The extra 6 damage over a bludgeon at the cost of a daze doesn't seem worthwhile.
Meteor Shower (R)(1) - Works well as is.
Mind Over Matter (R)(1) - Works well enough, perhaps not for its rarity.
Nexus (R)(2) - Amazing concept, nightmare to actually use without certain card combos.
Periapt of Celerity (R)(2) - Works well as is.
Periapt of Potency (R)(2) - Works well as is.
Power Overwhelming (R)(1) - Works well, but only in combination with brilliance or Enigma. Otherwise unplayable except in conjunction with a killing blow.
Reflection (R)(2) - Works well in Librarian-esque decks
Thought Raze (R)(2) - Works well, completely overpowering with quite a few combos.
Zenith (R)(1) - Works well as is.

Alternative Card Abilities:
Astral Haze - Converted into a power with a lesser debuff, or as a 0 cost skill.
Convergence - Chose an card to upgrade, upgrade all cards in hand on upgrade.
Surge - Lesser damage, but hits 1 additional time per debuff type.
Void ray - Remove dazed and/or add 1 weak / 1 vulnerable debuff.

Archives - Energy cap, slightly lower card requirements
Coalescence - 3 block for each 1 weak, vulnerable, and frail
Flare - Add 1 weak, in addition to its 1 vulnerable. As is it's an on par slice without the draw to make it as useful.
Enigma - Change to when a card exhausts, as is it is too easily abuse-able with certain card synergies. This would also fix quite a few interactions and bring a smoother balance to the play style. The other alternatives feel like good suggestions, this one seems completely necessary.
Gravity Well - target all enemies instead of single target.
Nova - reduced cost on upgrade and/or slightly increased damage on upgrade.
Plasma Wave - Convert into X cost irradiate, ie 1 vulnerable / 1 weak per hit.
Shimmer - Remove exhaust instead of defense buff on upgrade.
Singularity - Reduce cost on upgrade.
Syzygy - Remove exhaust effect.
Wormhole - Reduce cost on upgrade.

Chaos Form - Reduce cost and / or reduce cost again on upgrade.
Dimension Door - Reduce cost on upgrade
Eclipse - Remove topcycle or exhaust, as either upgrade or inherent.

I've currently logged 12 hours with this character concept with a 20% win rate. The same 12 hours with the Ironclad and Silent are 90% and 60% consecutively. I Currently have over 100 hours with the Ironclad, and almost 50 with the Silent. My win percentage has gone up even after the 12 hour mark, but I don't feel the concept will reach either of those percentages currently. As is the current meta the concept feels vastly under powered except with certain overpowering card combos that require a minimum of 3 cards of uncommon or rare rarity to accomplish. I feel like the suggestions and ratings provided will go a long way towards reaching a rating somewhere in between the success rating of both the Ironclad and Silent.

**Comment by gskleres** [comment]
Thank you for this! Will consider your feedback as next version is being developed! :)
