### ISSUE TITLE
Intangible bug

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#167]
Intangible doesn't work on thorns (from Dimension Door ability). This occurs when fighting things like the spikers from act 3

**Comment by Meow-Mixer** [comment]
It doesn't work on any triggered effect, only attacks. The exploder still does full damage as well.

**Comment by gskleres** [comment]
@Meow-Mixer can we find a way to make it work on those as well? Nemesis reduces its damage to 1 from things like Caltrops as well, which trigger on attacks against the player.

**Comment by Meow-Mixer** [comment]
There are 2 possibilities I can think of. Either the effect doesn't last quite long enough, or regular damage and effect damage are 2 different nomenclature. If it's the first issue I would have the effect last until the beginning of the next turn. If it's the latter I would look at the code behind Nemesis for the nomenclature.

**Comment by gskleres** [comment]
Implemented, needs testing.
