### ISSUE TITLE
Power Overwhelming & Enigma bug

### ISSUE THREAD

**Issue by corwinburdick** [gskleres/FruityMod-StS#169]
## Expected Behavior
After playing both powers, playing a Dazed should recycle 1 Dazed to the draw pile and discard the played Dazed.

## Actual Behavior
Playing a Dazed recycles 2 Dazed into the draw pile and discards the played Dazed

This made for a very easy run thanks to Unceasing Top + the relic that heals on exhausted ethereal cards. After a few setup turns, I could play infinite numbers of Dazed while growing my draw pile.

It's possible there was some other interaction going on that was causing this. I can upload the run history if needed.

**Comment by gskleres** [comment]
@corwinburdick did you have Enigma power active as well?

**Comment by corwinburdick** [comment]
@gskleres Enigma is the one that lets you play Dazed for 1 dmg/1 block, right? If so, then yes, both Power Overwhelming and Enigma were active.

**Comment by Meow-Mixer** [comment]
That is a bug in the Enigma structure, when you play a daze it counts as 2 cards played.

**Comment by gskleres** [comment]
This is solved by the new Enigma, which transforms Dazed into a separate attack card #73
