### ISSUE TITLE
Card 8 Comet

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#17]
Card 8

Name: Comet
Rarity: 1-Common
Type: Attack
Basic [1 cost]: Deal 2 damage for each other card in your hand.
Upgrade [1 cost]: Deal 3 damage for each other card in your hand.

**Comment by gskleres** [comment]
Named changed from "Magic Missile" to "Comet"

**Comment by gskleres** [comment]
BUG: Using "deck add Comet" and "deck add Comet 1" do not work at all.

**Comment by gskleres** [comment]
This card is incorrectly adding a Dazed to the draw pile on cast, in both the regular and upgraded versions.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Dumped old card, now is 1(1) cost: Deal 5(8) damage. Deals an additional 1(2) damage for ALL of your Ethereal cards. Rarity increased from Common to Uncommon.

**Comment by daviscook477** [comment]
Comet isn't checking the exhaust pile right now

**Comment by daviscook477** [comment]
Works!

**Comment by fiiiiilth** [comment]
This was actually due to Convergence not having "isEthereal = true". I've committed the fix for it.

**Comment by gskleres** [comment]
Works!
