### ISSUE TITLE
Mind Over Matter unplayable without debuffs on the player

### ISSUE THREAD

**Issue by ImelchorI** [gskleres/FruityMod-StS#172]
The card sadly ruined a spinning top run for me, since it broke my draw chains.

would it be possible to please make it playable without debuffs on the player and just grant 0 block in that case?

**Comment by gskleres** [comment]
@ImelchorI Good point! Will fix.

**Comment by gskleres** [comment]
Implemented.

**Comment by ImelchorI** [comment]
nice, thank you. 

i noticed this with certain other cards like transference aswell. i might be wrong, but doesnt the game generally allow to play cards, unless explicitly stated that they need some other condition that isnt met? like essence dart, or clash, which need certain other cards i hand. 

but cost or no cost, most cards are always playable even if they dont have an effect or only a partial effect. survivor from the silent default deck can be played as the last card in hand for example, even when there is nothing to discard.
