### ISSUE TITLE
Channel + Dazed

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#178]
Celerity had a bug by which he played Channel+ with only one other card in his hand, a Dazed. The Dazed auto discarded, but he did not get the extra proc of 10 damage which he should have because Dazed is Ethereal. It might be related to fast mode being on, ending the turn faster than the channel can trigger the discard proc?

**Comment by Meow-Mixer** [comment]
That is a fast play bug like you said, not necessarily a celerity bug.

**Comment by gskleres** [comment]
This is solved by the new Enigma, which transforms Dazed into a separate attack card #73
