### ISSUE TITLE
Card Art

### ISSUE THREAD

**Issue by OmnomMo** [gskleres/FruityMod-StS#179]
I might be able to do a few illustrations for Seeker cards.

Here's a few examples of (somewhat) finished pieces:
http://fav.me/dc5gtuq
http://fav.me/dc4kd3p
http://fav.me/dc68ywx
http://fav.me/dc4tc24

If you're interested I'd be glad to help.

**Comment by gskleres** [comment]
@OmnomMo Yes please! Could you email me directly? george.skleres@gmail.com - we can coordinate a bit easier from there.
