### ISSUE TITLE
Card 9 Retrograde

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#18]
Card 9

Name: Retrograde
Rarity: 1-Common
Type: Attack
Basic [0 cost]: Deal 4 damage. Shuffle a copy of this card into your draw pile at the end of the turn.
Upgrade [0 cost]: Deal 6 damage. Shuffle a copy of this card into your draw pile at the end of the turn.

**Comment by gskleres** [comment]
BUG: Currently shuffles a copy into discard pile. Should shuffle into draw pile.

**Comment by daviscook477** [comment]
I knew about that bug and forgot to report it. Oops. It shouldn't be tough to fix.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Copy shuffle now happens at end of turn.

**Comment by gskleres** [comment]
BUG (COSMETIC): Card text doesn't mention about it being end of turn.

(I fixed this in my commit).

**Comment by daviscook477** [comment]
Works!
