### ISSUE TITLE
Duplicate Seeker Sprites

### ISSUE THREAD

**Issue by Lunaraia** [gskleres/FruityMod-StS#183]
## Expected Behavior
When you die/return to main menu the old sprite of the Seeker is supposed to clear out

## Actual Behavior
When you quit and return to main menu then either start a new run or resume an old one an additional seeker sprite is visible usually slightly out of synch with the current one, every subsequent return to the main menu and resume in this fashion adds another

## Steps to Reproduce the Problem

  1. start a run as seeker
  1. die or quit to main menu
  1. resume or start a new run as The seeker

## Specifications

  - Version: newest as of writing this
  - Platform: PC, not sure why this is needed?
  - Subsystem: not sure what this means

**Comment by fiiiiilth** [comment]
@Lunaraia This was an issue on BaseMods end, which has now been fixed. Just make sure ModTheSpire, BaseMod and FruityMod are all up to date.
