### ISSUE TITLE
Stroke of Genius buff pls?:(

### ISSUE THREAD

**Issue by SirHaesslich** [gskleres/FruityMod-StS#186]
I reckon you do a lot of testing and balancing, but one card makes me scratch my head....
The Stroke of Genius - the skill that puts a random Power in your hand(cost 1, exhaust, on upgrade removes the cost of the generated Power, becoming an Infernal Blade analogy) - every time I used it, it felt very powerful yet not busted with only one tiny "but": it was literally useless unless upgraded, since if you are on 3 energy and get a 3 energy power, you cannot even play it, and randomness of the result combined with mana clunkiness made it impossible to get good results without first-priority spending an upgrade on it. At the time, I thought that it is my problem as a player, but then Defect came out, sporting almost the same version of a card, only much better - the base version is like Seeker's upgraded. Now, I also am well aware that a random Defect power is on average good and useful only in that deck archetype where you care more about the fact it is a power that what does it do(Storm build) and most of Seeker's powers are not useless(and usually really nice) in any of his deck variations, but the unupgraded version really feels so sad every time, maybe a slight buff?

**Comment by fiiiiilth** [comment]
@SirHaesslich Thanks for the feedback! When I saw White Noise, I thought about the same thing. Obviously it's not always fair to compare similar cards across different decks, but I think in this case it applies. 

The easiest buff would be just making it a copy of Infernal Blade/Distraction/White Noise. 

Any thoughts on that, or other ideas?

**Comment by SirHaesslich** [comment]
Well, the buffed version seems fine for me(I mean, come on, both
Periapts, Wormhole, Chaos Form, PO, Enigma -- pulling those off for
one mana even at the cost of consistency is real awesome); one of my
thoughts about the basic one was discounting the power by 1 or 2(
maybe by 2? So that you still have to pay up for most expensive cards,
but if you pull out something less impressive, you kinda already spent
some energy). Also that can be applied to the upgraded version as
well, but also make it upgrade the power. Or, as a variation of the
same idea AND to make a card different, you can make it discount the
card only by 1 but upgrade the power even when it is pulled by the
basic SoG. And cheapen the upgrade by 1. It will give the card some of
its own features compared to White Noise, and both upgraded and basic
versions of cards will have their stronger and weaker sides in
comparison( in short, SoG will be stronger but more mana-heavy, which,
combined with Seeker's lack of insane mana generation that Defect is
known for, should compensate the difference in the strength of an
average power)

Hope this helps!

2018-05-15 17:53 GMT+03:00, fiiiiilth <notifications@github.com>:

**Comment by fiiiiilth** [comment]
Those are some great idea's that I hadn't really considered. I'll implement something along these lines when I can and get another release out for you to test.

**Comment by SirHaesslich** [comment]
A big fat thank you :D

2018-05-15 21:01 GMT+03:00, fiiiiilth <notifications@github.com>:

**Comment by gskleres** [comment]
@fiiiiilth @SirHaesslich just reduce the cost of this card to 0 for both unupgraded and upgraded versions.

**Comment by gskleres** [comment]
Or if that's too strong, make it top cycle the card you create so that you lose 1 card draw next turn.
