### ISSUE TITLE
Reflection Ward, the unexpected carry

### ISSUE THREAD

**Issue by SirHaesslich** [gskleres/FruityMod-StS#187]
## Expected Behavior
So the card description says that Reflect deals damage back to the attacker(like with Caltrops or Spiker's Spiky Spikes)

## Actual Behavior
But when I got it, every time I played it, it dealt the Reflect damage in AoE, effectively wiping out the entire population of the Spire. Even when there are only 2 enemies, it feels really powerful. Is it intended behavior and just a bad wording or is it a bug?

## Steps to Reproduce the Problem

  1. I did it way more than once, just play it and look. Make sure the number of enemies is more than 1.
  2. If this may help, I got it only on Beyond stage.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by fiiiiilth** [comment]
Yeah, I think there was some confusion when Reflect was added over whether the damage was supposed to be AoE and the keyword was wrong, or the other way around.

I've had it before and it is indeed powerful. Could probably use a nerf.

**Comment by gskleres** [comment]
It's intended behavior. The card is rare and you have to draw it at the
right time. The tooltip is wrong.
