### ISSUE TITLE
It is OK the ideas of new character?

### ISSUE THREAD

**Issue by hyugjun** [gskleres/FruityMod-StS#188]
Hello, I played this fruitymod well. 

I have some new idea for new character of the slay the spire mod, so i want share my Ideas of them.

It have some new keywords. 

For example, character concepted samurai, has keyword 
**_Batto X_** - deal X by draw that card. 
**_Repetition_** - it gain more effect characters health is under 50%. 
**_Combo_** - you gain bonus already played a card this turn.

like this thing, i have some characters idea. and thinked the concept of that characters.

**Comment by SirHaesslich** [comment]
I think this is the wrong place to write that stuff, they are currently doing quite a bit of work on The Seeker to make him as polished as possible, so dropping just 3 random keywords on already busy people is at least inconsiderate

**Comment by fiiiiilth** [comment]
@hyugjun I don't mind too much that you posted it here, but as @SirHaesslich mentioned, it's not really the best place for it. I'd post it on Slay the Spire's subreddit, or their Steam discussions. I've noticed people have gotten ideas from there in the past for mod relics/cards/mechanics, etc...
