### ISSUE TITLE
Card 10 Magic Missile

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#19]
Card 10

Name: Magic Missile
Rarity: 1-Common
Type: Attack
Basic [1 cost]: Ethereal. Deal 3 damage 4 times. Exhaust.
Upgrade [1 cost]: Ethereal. Deal 3 damage 5 times. Exhaust.

**Comment by gskleres** [comment]
Name changed from Starfall to Magic Missile. NOTE: Card 8 used to be Magic Missile, so you probably have to do that rename first or else there will be a class name clash.

**Comment by gskleres** [comment]
BUG: When I use "deck add MagicMissile" it gives me a copy of Comet instead.

**Comment by gskleres** [comment]
BUG: Using "deck add MagicMissile" and "deck add MagicMissile 1" has no effect. Card is not in game.

**Comment by gskleres** [comment]
BUG: Number of attacks and/or card text are not working correctly. Regular version says "Deal 3 damage 1 times" but correctly attacks 4 times. Upgraded version says "Deal 3 damage 2 times" and also incorrectly attacks 2 times (instead of 5).

**Comment by fiiiiilth** [comment]
All of the above issues should be fixed. Comet and Magic Missile are now named/IDed correctly and the amount of attacks should be correct.

**Comment by gskleres** [comment]
Works!
