### ISSUE TITLE
Add github tag?

### ISSUE THREAD

**Issue by Daenyth** [gskleres/FruityMod-StS#195]
Can you add the `SlayTheSpire-Mod` tag? This will make the project easier for people to find

**Comment by fiiiiilth** [comment]
I unfortunately don't have the ability to edit this repos topics. I'll tag Fruitstrike to see if he can at some point.

@gskleres Could you do this?

**Comment by gskleres** [comment]
How does one do it? I don't see a tag option anywhere in the settings.

**Comment by fiiiiilth** [comment]
@gskleres On the main page of the repo, under the description at the very top, there should be a button to "Add topics".

**Comment by gskleres** [comment]
Done. I think?

**Comment by fiiiiilth** [comment]
@gskleres You got it, thanks!
