### ISSUE TITLE
Wrong path of card backgrounds

### ISSUE THREAD

**Issue by Opsi** [gskleres/FruityMod-StS#199]
## Expected Behavior
the skill and power cards of the seeker should use the respective card backgrounds.

## Actual Behavior
they all use the attack card background

The problem is a small mistake (probably from copy pasting) in the lines 79, 80, 84, 85 in FruityMod.java, where ATTACK_PURPLE, SKILL_PURPLE and POWER_PURPLE all refer to the same String.

This is first issue I ever made for someone else on github so please forgive and inform me, if I did something wrong.

![image](https://user-images.githubusercontent.com/5853305/42872764-15a0717c-8a7e-11e8-88d6-eed969c6e38f.png)

**Comment by fiiiiilth** [comment]
Oh, weird. Never noticed this somehow. Thanks for letting me know.
