### ISSUE TITLE
Card 12 Prismatic Sphere

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#21]
Card 12

Name: Prismatic Sphere
Rarity: 1-Common
Type: Attack
Basic [1 cost]: Ethereal. Deal 7 damage. Draw 2 cards.
Upgrade [1 cost]: Ethereal. Deal 11 damage. Draw 2 cards.

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic): Rename in game name to Prismatic Sphere.

**Comment by gskleres** [comment]
Works!
