### ISSUE TITLE
Card 13 Flux

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#22]
Card 13

Name: Flux
Rarity: 1-Common
Type: Attack
Basic [1 cost]: Ethereal. Gain 6 Block. Deal 6 damage.
Upgrade [1 cost]: Ethereal. Gain 8 Block. Deal 8 damage.

**Comment by gskleres** [comment]
Damage and Block reduced from 6/6(9/9) to 6/6(8/8).

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic): Rename in game name to Flux.

**Comment by gskleres** [comment]
Works!
