### ISSUE TITLE
Compendium crash

### ISSUE THREAD

**Issue by Tremor61** [gskleres/FruityMod-StS#229]
## Actual Behavior
The game crashes when opening the compendium

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by boommies** [comment]
Looking at the existing game's behavior, I think the better approach might be to always load the Tranquil cards, and leave them Locked in the Compendium.  Then change the tranquil_enabled=true behavior to:
    1) Unlock the cards
    2) Allow Tranquil to be selected on character selection
    3) Make Tranquil-related relics available.

**Comment by Tremor61** [comment]
How do i manually enable that to be true?

**Comment by boommies** [comment]
When you run the ModTheSpire jar, you need to pass the parameter tranquil_enabled=true.  Eg: `java -Dtranquil_enabled=true -jar ModTheSpire.jar`

**Comment by boommies** [comment]
A fix (described above) was made, and added to a new v1.0.0 release.  Wanna give that a whirl, and confirm that it resolves your issue?
