### ISSUE TITLE
Defaults to Ironclad

### ISSUE THREAD

**Issue by Picklerbob** [gskleres/FruityMod-StS#236]
I am getting a bug where I am automatically defaulted to the Ironclad every time I try to play a Mod class.

Does anyone know a fix?

**Comment by SilentJ28** [comment]
@Picklerbob Fixed it here: https://github.com/SilentJ28/FruityMod-StS/releases/tag/v1.0.1

**Comment by SilentJ28** [comment]
@gskleres Added the change to https://github.com/gskleres/FruityMod-StS/pull/234

**Comment by boommies** [comment]
Thanks for the fix!  Applied, verified, and release pushed.

**Comment by boommies** [comment]
Closing, fix in Release v1.0.1 - https://github.com/gskleres/FruityMod-StS/releases/tag/v1.0.1
