### ISSUE TITLE
Card 15 Flicker

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#24]
Card 15

Name: Flicker
Rarity: 1-Common
Type: Skill
Basic [0 cost]: Frail, Weak, and Vulnerable have the opposite effect on you for 1 turn.
Upgrade [0 cost]: Frail, Weak, and Vulnerable have the opposite effect on you for 2 turns.

**Comment by gskleres** [comment]
BUG: After Essence Mirror has been cast, click and drag a card, but do not release. The sound and effect animation play endlessly over and over until you stop dragging the card.

**Comment by daviscook477** [comment]
Cannot reproduce

**Comment by gskleres** [comment]
[EssenceMirrorBug.zip](https://github.com/gskleres/FruityMod-StS/files/1741324/EssenceMirrorBug.zip)

@daviscook477 Here is a video of the bug (GitHub required a zip file instead of the flv directly). I start by casting Power -Overwhelming and Coalescence and Essence Spike so that I can get some each of Vulnerable, Frail, and Weak. Then next turn I cast Essence Mirror. After casting, I drag cards in my hand around. You'll see the animation play in an infinitely stack loop on my character while I drag. I don't know why the video didn't record sound, but the buff noise plays in an infinitely stacking loop as well.

**Comment by daviscook477** [comment]
Fixed by removing the flash effect - applying the flash effect was going to be too finicky anyways (and current powers that affect dmg and block like frail or weak don't use the flash effect so this helps with consistency anyways)

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic): Rename in game name to Flicker.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Cost decreased from 1(0) to 0(0). Number of turns increased from 1(1) to 1(2).

**Comment by gskleres** [comment]
Updated
