### ISSUE TITLE
Card 16 Pulse Barrier

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#25]
Card 16

Name: Pulse Barrier
Rarity: 1-Common
Type: Skill
Basic [1 cost]: Gain 11 Block. Gain 2 Frail.
Upgrade [1 cost]: Gain 15 Block. Gain 2 Frail.

**Comment by gskleres** [comment]
Block reduced from 11(15) to 11(14).

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic): Rename in game name to Pulse Barrier.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Block increased from 11(14) to 11(15).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Pulse Barrier internal description is hard coded - it's not responding to changes in the JSON.

**Comment by gskleres** [comment]
Works!
