### ISSUE TITLE
Card 17 Nebula

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#26]
Card 17

Name: Nebula
Rarity: 1-Common
Type: Skill
Basic [1 cost]: Gain 2 Block for each other card in your hand.
Upgrade [0 cost]: Gain 2 Block for each other card in your hand.

**Comment by gskleres** [comment]
Block per Ethereal card reduced from 5(8) to 4(7).

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic): Rename in game name to Nebula.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Added Ethereal (works on itself).

**Comment by gskleres** [comment]
BUG (COSMETIC): The text in parenthesis at the bottom of the card summarizing the total is missing.

**Comment by gskleres** [comment]
Card works correctly. However, I am unable to update the text so it doesn't spill up past the text frame because the bonus text is hard-coded instead of in the localization file.

I went in and changed both the string in the java code and the json localization file to make it fit better.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Design updated: [1(0) cost]: Gain 2 Block for each other card in your hand.
