### ISSUE TITLE
Card 20 Singularity

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#29]
Card 20

Name: Singularity
Rarity: 1-Uncommon
Type: Attack
Basic [3 cost]: Ethereal. Gain 12 Block. Deal 12 Damage. Next turn gain 1 Energy.
Upgrade [3 cost]: Ethereal. Gain 15 Block. Deal 15 Damage. Next turn gain 1 Energy.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
BUG: Umbral Wave+ not triggering thorns damage from the guardian. Unsure of interaction with spikers or unupgraded Umbral Wave. Need to reclassify as Attack. Updated above.

BUG: Additional issue. Unupgraded Umbral Wave gives -1 energy the following turn, instead of +1. But only if used on the first turn of combat. Idk how that happened.

**Comment by dvalldejuli** [comment]
magic number was not being set, which is the reason for -1.

Guardian interaction see http://slay-the-spire.wikia.com/wiki/The_Guardian, as a skill card, this doesn't trigger the damage so this isn't a bug. Updated to attack, but easy to change back if that's the only reason you set the type to attack.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Rarity increased from Common to Uncommon. Energy gain next turn reduced from 1(2) to 1(1).

**Comment by gskleres** [comment]
Works!
