### ISSUE TITLE
Card 21 Genesis

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#30]
Card 21

Name: Genesis
Rarity: 1-Common
Type: Skill
Basic [1 cost]: Ethereal. Gain 6 Block. Draw 2 Cards.
Upgrade [1 cost]: Ethereal. Gain 9 Block. Draw 2 cards.

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic):
Currently an atk rather than a skill.

**Comment by dvalldejuli** [comment]
fixed

**Comment by gskleres** [comment]
BUG: Card name in game still says "Void Barrier" and "Void Barrier+"

**Comment by gskleres** [comment]
Works!
