### ISSUE TITLE
Card 22 Dark Matter

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#31]
Card 22

Name: Dark Matter
Rarity: 2-Uncommon
Type: Attack
Basic [1 cost]: Deal 3 damage for each Ethereal card that has been Exhausted this combat.
Upgrade [1 cost]: Deal 5 damage for each Ethereal card that has been Exhausted this combat.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Old card dumped. New card: Deal 3(5) damage for each Ethereal card that has been Exhausted this combat.

**Comment by daviscook477** [comment]
Should it be able to be cast if there are 0 exhausted ethereal cards?

**Comment by daviscook477** [comment]
Current implementation will prevent use if number of exhausted ethereal cards is 0 with a message "I do not have any exhausted ethereal cards"

**Comment by daviscook477** [comment]
Nevermind. I didn't like that idea. Current implementation always allows use. Sometimes it can deal 0 damage.

**Comment by daviscook477** [comment]
Should Dark Matter be multi-hit like Ether Blast?

**Comment by gskleres** [comment]
No, single hit.

**Comment by gskleres** [comment]
Works! Adjusted text on card so it doesn't spill over text frame

**Comment by gskleres** [comment]
Works!
