### ISSUE TITLE
Card 23 Entropy

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#32]
Card 23

Name: Entropy
Rarity: 2-Uncommon
Type: Skill
Basic [1 cost]: Ethereal. Enemy loses 2 Strength this turn, increasing by 1 each time this card is drawn this combat.
Upgrade [1 cost]: Ethereal. Enemy loses 3 Strength this turn, increasing by 1 each time this card is drawn this combat.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Damage adjusted from 5(6) to 5(8). Cost reduced from 2(1) to 1(1). Effect changed to Enemy loses 1(2) Strength this turn. These values increase by 1 every time you play this card. Full text: Deal 5(8) damage. Enemy loses 1(2) Strength this turn. Increase this card's values by 1 until end of combat.

**Comment by daviscook477** [comment]
Wording is very confusing and also the card text is too big and overflows.

**Comment by gskleres** [comment]
Changed from Attack to Skill. Damage removed. Card text now reads: "Ethereal. Enemy loses 2 Strength this turn, increasing by 1 each time this is played this combat."

**Comment by daviscook477** [comment]
I think is probably a way OP version of Disarm. http://slay-the-spire.wikia.com/wiki/Disarm. Same strength loss, no exhaust, and does more strength loss each time? Probably waay too good.

**Comment by gskleres** [comment]
@daviscook477 Disarm is permanent for the rest of battle. This card is only strength loss till the end of turn - you have to redraw it to apply it again.

**Comment by daviscook477** [comment]
Right

**Comment by daviscook477** [comment]
Ignore that previous comment about it being OP. Apparently I can't read

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Updated: No longer Ethereal. Increase of strength debuff now occurs on draw instead of on play.

**Comment by gskleres** [comment]
Back to Ethereal again! :D
