### ISSUE TITLE
Card 24 Phase Coil

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#33]
Card 24

Name: Phase Coil
Rarity: 1-Common
Type: Attack
Basic [2 cost]: Deal 9 damage. Whenever you draw this card, increase the damage by 3 this combat.
Upgrade [2 cost]: Deal 15 damage. Whenever you draw this card, increase the damage by 3 this combat.

**Comment by gskleres** [comment]
Rarity decreased from Uncommon to Common.

**Comment by gskleres** [comment]
BUG: Card text on both regular and upgrade says "Costs -1 less" but should say "Costs 1 less". This is purely cosmetic - the card behavior works perfectly despite the text error.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Damage reduced from 15(20) to 15(18). Cost reduced from 4(4) to 4(3).

**Comment by gskleres** [comment]
BUG: Non-upgraded card shows 4 cost in Red, upgraded card shows 1 cost in Green. This was with 0 Ethereal cards in hand. Both of these should be regular white text for cost and they should show 4 and 3, respectively. 

The cards still correctly reduce cost by 1 for each ethereal card added to hand, and they also correctly show green text after the cost has been reduced.

**Comment by daviscook477** [comment]
Could not reproduce.

**Comment by fiiiiilth** [comment]
I had already fixed the issue, I just put the wrong number for the upgraded cost. I don't think anything can be done about the 4 being red if you don't have 4 energy though.

**Comment by gskleres** [comment]
Oh duh right @fiiiiilth I forgot the cost is automatically made red if you can't afford it. Thank you, ignore my comment!

Works!

**Comment by gskleres** [comment]
Design Update: Deal 9(15) damage. Whenever you draw this card, increase the damage by 3 this combat.
