### ISSUE TITLE
Card 25 Plasma Wave

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#34]
Card 25

Name: Plasma Wave
Rarity: 2-Uncommon
Type: Attack
Basic [X cost]: Spend all Energy. Deal 3 damage to ALL enemies. Vulnerable enemies take double damage.
Upgrade [X cost]: Spend all Energy. Deal 5 damage to ALL enemies. Vulnerable enemies take double damage.

**Comment by gskleres** [comment]
Damage reduced from 7(10) to 6(9) per Energy spent.

**Comment by gskleres** [comment]
BUG: I was able to cast EssenceShred when no enemies were Weak or Vulnerable. It did the Whirlwind slash animation 3 times but no damage numbers ever came up. It is correct that it should do no damage, but would be better if we can get it to simply not be cast-able without at least one valid target. Is this possible?

BUG: The slash animation goes over ALL enemies instead of just the Weak and Vulnerable ones.

**Comment by dvalldejuli** [comment]
Added a use check for monsters with Weak or Vulnerable

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Now deals base 3(5) damage to ALL enemies X times. Vulnerable enemies are damaged twice as many times.

**Comment by daviscook477** [comment]
So if I cast this for 1 and there's an enemy that's vulnerable and an enemy that's not vulnerable on the field is this how the calculation goes? The not vulnerable enemy takes 3 damage. The vulnerable enemy takes 3*2=6 -> 9 (b/c +50% for vulnerable) damage?

**Comment by daviscook477** [comment]
I got it working. Yay!

**Comment by gskleres** [comment]
Yes that's correct! Card works!
