### ISSUE TITLE
Card 26 Ether Blast

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#35]
Card 26

Name: Ether Blast
Rarity: 2-Uncommon
Type: Attack
Basic [2 cost]: Ethereal. Deal 6 damage, plus 2 damage for ALL of your Ethereal cards.
Upgrade [2 cost]: Ethereal. Deal 10 damage, plus 3 damage for ALL of your Ethereal cards.

**Comment by gskleres** [comment]
Damage increased from 5(7) to 5(8).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Added Ethereal. Rarity decreased from Uncommon to Common. 

BUG: Damage is currently dealt as one big hit, with Strength applied once. Damage should now dealt individually (instead of tallied and applied once), so strength applies per hit. Card text updated to match.

**Comment by daviscook477** [comment]
Did design update and fixed bug

**Comment by gskleres** [comment]
I am an idiot - I put the comment on the wrong card, I'm pretty sure - it should be 1x strength bonus, not strength bonus per 5 damage dealt. We discussed, sorry!!

**Comment by gskleres** [comment]
Ok apologies for being a derp on this card, @daviscook477 . Here's what the final behavior looks like. Assume 4 Ethereal cards in hand and 1 Strength:

* Ether Blast would deal 21 damage (4 Ethereal cards X 5 damage per card, +1 for Strength)
* Ether Blast+ would deal 33 damage (4 Ethereal cards X 8 damage per card, +1 for Strength)

Formula: (NumEtherealCards X DamagePerEtherealCard) + StrengthBonus

Also can you make the animation be a single attack instead of multiples?

**Comment by gskleres** [comment]
Are you sure you updated this @daviscook477 ? I am testing now with latest and it's exactly the same as the previous version without the fix. Was there a mistake with releasing FruityMod jar?

**Comment by gskleres** [comment]
BUG (cosmetic): The text "(You have X Ethereal cards in hand)" is now extraneous since it shows damage total beneath it and causes it to go outside the card text borders by a lot. That text should be removed.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Design Overhaul: [2 Cost]: Ethereal. Deal 6(10) damage, plus 2(3) damage for ALL of your Ethereal cards.
