### ISSUE TITLE
Card 29 Force Ripple

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#38]
Card 29

Name: Force Ripple
Rarity: 3-Rare
Type: Attack
Basic [X cost]: Spend all Energy. Deal 12 damage X times. Gain X Weak, X Frail, and X Vulnerable.
Upgrade [X cost]: Spend all Energy. Deal 16 damage X times. Gain X Weak, X Frail, and X Vulnerable.

**Comment by gskleres** [comment]
BUG: Also creates and shuffles a copy of itself into the draw pile instead of just discarding itself. This happens with both the regular and the upgraded version of the card.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Dumped old card, new card - Rare Attack, costs X: Spend all Energy. Deal 13(18) damage X times. Gain X Weak, X Frail, and X Vulnerable.

**Comment by daviscook477** [comment]
BUG: currently Force Ripple applies X^2 stacks of weak, vulnerable, and frail.

**Comment by daviscook477** [comment]
Should be fixed now.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Updated: Damage reduced from 13(18) to 12(16).
