### ISSUE TITLE
Card 30 Siphon Power

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#39]
Card 30

Name: Siphon Power
Rarity: 2-Uncommon
Type: Attack
Basic [2 cost]: Deal 10 damage. Apply 1 Vulnerable. Gain 1 Strength.
Upgrade [2 cost]: Deal 14 damage. Apply 2 Vulnerable. Gain 1 Strength.

**Comment by daviscook477** [comment]
Is it supposed to apply weak to the player?

**Comment by gskleres** [comment]
Design updated (first comment is updated version). Old version for archiving:

Name: Siphon Power
Rarity: 2-Uncommon
Type: Attack
Basic [2 cost]: If an enemy intends to attack, deal 10 damage and gain 1 Strength.
Upgrade [2 cost]: If an enemy intends to attack, deal 13 damage and gain 2 Strength.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
DESIGN UPDATE: Strength gain reduced from 1(2) to 1(1).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Apply Weak changed to Apply Vulnerable. Damage increased from 8(10) to 8(11).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Updated: Damage increased from 8(11) to 10(14).
