### ISSUE TITLE
Card 34 Gravity Well

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#43]
Card 34

Name: Gravity Well
Rarity: 2-Uncommon
Type: Skill
Basic [1 cost]: If the enemy is Weak, it loses 3 Strength. Exhaust.
Upgrade [1 cost]: If the enemy is Weak, it loses 4 Strength. Exhaust.

**Comment by gskleres** [comment]
Strength loss while Weak reduced from 2(3) to 1(2).

**Comment by gskleres** [comment]
Current card in game is a Skill. Should be a Power.

**Comment by daviscook477** [comment]
I made it a skill because the implementation gives a debuff to all enemies rather than a buff to the player. It seems more consistent with the type conventions in the game currently that way

**Comment by gskleres** [comment]
@daviscook477  It's castable over and over then, and stacks infinitely. The design would have to be changed considerably to prevent abuse. Is it impossible to do as a Power?

**Comment by daviscook477** [comment]
Good point - so add exhaust?

**Comment by gskleres** [comment]
But then it doesn't interact with the other stuff correctly. For example, it cannot be randomly spawned via Stroke of Genius.

**Comment by daviscook477** [comment]
I agree that it will change interactions but I really don't think that it should be a power if it's debuffing enemies rather than being a buff to the player.

**Comment by gskleres** [comment]
Do you mean a skill? I also think it should be a power. ;)

**Comment by gskleres** [comment]
Powers can hurt enemies just like Skills. For example, Noxious Fumes.

**Comment by daviscook477** [comment]
They can hurt enemies. But to apply a negative debuff to the enemy it would have to be a power on the enemy character (not on the player character). Otherwise we could just change it to additional damage negation from weakened enemies (I think?)

**Comment by gskleres** [comment]
Card redesigned in a way that's easier to program but still accomplishes the same goal.

**Comment by gskleres** [comment]
We're gonna leave as is and revisit later.

**Comment by gskleres** [comment]
Changed to Exhaust, since it's one time only now it does -3(-4) Strength. Wording updated.

**Comment by gskleres** [comment]
Works!
