### ISSUE TITLE
Card 35 Coalescence

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#44]
Card 35

Name: Coalescence
Rarity: 2-Uncommon
Type: Power
Basic [2 cost]: At the end of your turn, gain 2 Block for each stack of Frail, Weak, or Vulnerable you have.
Upgrade [2 cost]: At the end of your turn, gain 3 Block for each stack of Frail, Weak, or Vulnerable you have.

**Comment by gskleres** [comment]
35 Nexus replaced entirely (deck had too much Strength/Dexterity gain). Replaced with 35 Coalescence. Old card archived here:

Card 35

Name: Nexus
Rarity: 2-Uncommon
Type: Power
Basic [1 cost]: Whenever you play an attack, gain 1 Block.
Upgrade [1 cost]: Whenever you play an attack, gain 2 Block.

**Comment by daviscook477** [comment]
I honestly think no-one would play this card in its current state. It's a barely better `Metalicize` (1 more block) for perpetual -25% damage. Any way to balance better?

**Comment by gskleres** [comment]
It combos with several other cards in the set (Essence Mirror, Transference, Channel). This character currently has 2 paths, both deal with Ethereal but one tries to prevent any debuffs whatsoever and the other tries to get debuffed as much as possible to punish the enemies or buff self. You are probably right that the numbers are too low, but that's easy to change later if it proves that way. This class set is too strong as whole so I was looking for easy places to shave off a bit here and there.

**Comment by daviscook477** [comment]
Right I forgot about the part where this character sometimes likes being debuffed. Concerns withdrawn :)

**Comment by gskleres** [comment]
BUG: Upgraded version gives 4 Block, but should give 6 Block.

**Comment by gskleres** [comment]
Card slightly redesigned so that the weak is applied at the beginning of turn instead of end, that way it actually has any effect ever lol...

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
BUG: The tooltip for the status effect when you hover over your character after it's cast still says "end of turn"

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Old card dumped. New card: Uncommon Power, cost 1: Whenever you gain Frail, Weak, or Vulnerable, gain 3(5) Block.

**Comment by gskleres** [comment]
BUG: When enemy gives you Frail, Weak, or Vulnerable, this does not trigger. For example, I was fighting Maw (guaranteed turn 1 Frail + Weak) and I did not gain block for either of them.

**Comment by daviscook477** [comment]
Design changed to avoid bug because this card is awkward.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Design Update: At the end of your turn, gain 2(3) Block for each stack of Frail, Weak, or Vulnerable you have.
