### ISSUE TITLE
Card 39 Anomaly

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#48]
Card 39

Name: Anomaly
Rarity: 2-Uncommon
Type: Power
Basic [0 cost]: Whenever you apply Vulnerable or Weak to an enemy, apply 1 additional stack.
Upgrade [0 cost]: Whenever you apply Vulnerable or Weak to an enemy, apply 2 additional stacks.

**Comment by gskleres** [comment]
Renamed to Anomaly. Mechanics are identical.

**Comment by gskleres** [comment]
BUG: The power only affects the next card played for each type (weak / vulnerable). Other future cards of that type do not work. For example, if I play Anomaly, then play Flare, Flare, SiphonPower, the first Flare (applies Vulnerable) is affected by Anomaly, but not the 2nd. Then the SiphonPower is also affected by Anomaly because it's the first Weak effect played after Anomaly. This carries through to future turns, so once you've played a Weak or Vulnerable card, future cards of that type will not benefit from Anomaly.

**Comment by daviscook477** [comment]
Might be related to this `power.ID == "Weakened" || power.ID == "Vulnerable"` `==` for String equality is wrong

**Comment by daviscook477** [comment]
Probably has to do with power stacking then

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Updated: Cost reduced from 1(1) to 0(0).
