### ISSUE TITLE
Card 40 Vortex

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#49]
Card 40

Name: Vortex
Rarity: 2-Uncommon
Type: Skill
Basic [1 cost]: Draw until your hand is full. Recycle 4 Dazed. Exhaust.
Upgrade [0 cost]: Draw until your hand is full. Recycle 4 Dazed. Exhaust.

**Comment by dvalldejuli** [comment]
Unable to test due to mod loading issue after getting latest.

**Comment by gskleres** [comment]
DESIGN UPDATE: This card is trivializing boss fights (in particular Awakened One - you can play all your powers, then play this card afterwards). Design updated to never reduce strength anymore. Sorry! :(

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Old card dumped. New card is an Uncommon Skill, 1(1) cost: Gain 12(16) Block. Convert your hand to Dazed and shuffle it into your draw pile.

**Comment by gskleres** [comment]
This works in game, but it's an altered design that is a bit more powerful than the original design. @daviscook477 is there any way to transform a card in hand into another card without exhausting the original card? If not, no worries, we'll run with this version - I just need to know so I can update the design docs if it's impossible.

**Comment by daviscook477** [comment]
Can this card please be changed to:

Card 40

Name: Vortex
Rarity: 2-Uncommon
Type: Skill
Basic [1 cost]: Gain 12 Block. Exhaust your hand. Shuffle 1 Dazed into your draw pile for each card that was Exahusted.
Upgrade [1 cost]: Gain 16 Block. Exhaust your hand. Shuffle 1 Dazed into your draw pile for each card that was Exahusted.

**Comment by gskleres** [comment]
BUG (cosmetic): The word "Exhaust." for the card itself should be the last word, not the 2nd word.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
DESIGN UPDATED: Old card dumped (too similar to Shimmer). New card is as follows:

Vortex [Uncommon Skill, 1(0) Cost]: Draw until your hand is full. Recycle 4 Dazed. Exhaust.

**Comment by gskleres** [comment]
Works!
