### ISSUE TITLE
Card 42 Brainstorm

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#51]
Card 42

Name: Brainstorm
Rarity: 2-Uncommon
Type: Skill
Basic [0 cost]: Recycle your discard pile and this card. Next turn, draw 1 card.
Upgrade [0 cost]: Recycle your discard pile and this card. Next turn, draw 2 cards.

**Comment by gskleres** [comment]
Cost increased from 0(0) to 1(0). Card draw reduced from 2(3) to 2(2).

**Comment by dvalldejuli** [comment]
update complete

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Cost reduced from 1(0) to 0(0). Card draw delayed to next turn, and reduced from 2(2) to 1(2).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Card should no longer shuffle a Dazed. Should only shuffle itself and the discard pile.
