### ISSUE TITLE
Card 46 Magnetize

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#55]
Card 46

Name: Magnetize
Rarity: 2-Uncommon
Type: Skill
Basic [0 cost]: Gain 2 Block. Apply 1 Weak.
Upgrade [0 cost]: Gain 4 Block. Apply 2 Weak.

**Comment by gskleres** [comment]
46 Experiment entirely replaced by 46 Magnetize (the class had too much Str/Dex gain). But this effect can go on a future class so it's not wasted work. Archiving 46 Experiment here:

Card 46

Name: Experiment
Rarity: 2-Uncommon
Type: Skill
Basic [1 cost]: If an enemy intends to Debuff you, gain 1 Strength and 1 Dexterity.
Upgrade [1 cost]: If an enemy intends to Debuff you, gain 2 Strength and 2 Dexterity.

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug:
Causes enemies to have permanent weak stacks. It will never reduce the number of stacks unless an effect like Feedback is used.

**Comment by gskleres** [comment]
Works!
