### ISSUE TITLE
Card 48 Illuminate

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#57]
Card 48

Name: Illuminate
Rarity: 2-Uncommon
Type: Skill
Basic [0 cost]: Create and Recycle a copy of an Ethereal card in your hand.
Upgrade [0 cost]: Create and Recycle 2 copies of an Ethereal card in your hand.

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic): Illuminate+ says "Create 2 copy."

**Comment by gskleres** [comment]
Now shuffles the created cards into your draw pile.

**Comment by gskleres** [comment]
BUG: The bug is that the card creates the copies in your hand. Instead it should work like the design update below (I changed it after playtesting it during testing).

DESIGN UPDATE: Cost reduced from 1(1) to 0(0). When the copies are made, they should be placed on top of your draw pile. Card text updated to "Create and Recycle a copy (2 copies) of an Ethereal card in your hand."

**Comment by daviscook477** [comment]
I think using the recycle keyword here would be confusing. I'm going to word it as "Create a copy (2 copies) of an Ethereal card in your hand and put them on the top of your draw pile."

**Comment by gskleres** [comment]
Card text localization updated.

**Comment by gskleres** [comment]
Works!
