### ISSUE TITLE
Card 49 Mind Over Matter

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#58]
Card 49

Name: Mind Over Matter
Rarity: 3-Rare
Type: Skill
Basic [1 cost]: Remove all Frail, Weak, and Vulnerable. Gain 5 Block, plus 3 Block for each stack that was removed.
Upgrade [1 cost]: Remove all Frail, Weak, and Vulnerable. Gain 5 Block, plus 5 Block for each stack that was removed.

**Comment by gskleres** [comment]
Effect now grants 6 Block instead of Strength.

**Comment by daviscook477** [comment]
Is it intentional that the 6 Block being gained per stack of frail will be affected by the frail status, e.g. since the user is frail they will actually only gain 4 Block per stack instead of 6.

**Comment by gskleres** [comment]
Good catch ... let's reverse the order of this card's effects. :)

**Comment by daviscook477** [comment]
Alright sounds good

**Comment by daviscook477** [comment]
Suggested description. "Remove all Frail. Gain 6 Block for each stack of Frail removed."

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Cost increased from 2(1) to 2(2). Now also works with Weak and Vulnerable. Block amount per stack removed changed from 6(6) to 4(6).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Now also gives 5 Block base (in both versions).
