### ISSUE TITLE
Card 52 Shimmer

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#61]
Card 52

Name: Shimmer
Rarity: 2-Uncommon
Type: Skill
Basic [1 cost]: Gain 15 Block. All cards in hand become Ethereal. Exhaust.
Upgrade [1 cost]: Gain 20 Block. All cards in hand become Ethereal. Exhaust.

**Comment by gskleres** [comment]
Cost increased from 1(0) to 1(1). No longer gains Energy. Now gains 15(20) Block.

**Comment by gskleres** [comment]
BUG: Can we put the word "Ethereal. " at the beginning of the card text instead of the end when it's added? That way it matches the other cards that are Ethereal.

BUG: Card should Exhaust on use, but does not.

**Comment by gskleres** [comment]
"Ethereal." text added to beginning of card needs an additional space after it, and needs to be colored yellow.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Block reduced from 15(20) to 12(16).

**Comment by gskleres** [comment]
BUG (cosmetic): Non-Ethereal cards that are turned Ethereal which wind up in the exhausted card pile no longer say Ethereal. They should still say Ethereal.

**Comment by daviscook477** [comment]
Same as https://github.com/gskleres/FruityMod-StS/issues/122
This is not specific to Shimmer so I'm closing this issue.

**Comment by gskleres** [comment]
BUG(cosmetic): When I use this card with Zenith in my hand, it does not put a space after the "Ethereal." which means the keyword is not highlighted. The card still behaves as Ethereal though.

BUG(cosmetic): When I use this card with Reflection Ward in my hand, the text "Ethereal. " is not added to the beginning of the card.

**Comment by gskleres** [comment]
Works!
