### ISSUE TITLE
Card 53 Convergence

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#62]
Card 53

Name: Convergence
Rarity: 1-Common
Type: Skill
Basic [has no displayed cost]: Unplayable. When you draw this card, upgrade a card in your hand.
Upgrade [has no displayed cost]: Unplayable. When you draw this card, draw another card and upgrade a card in your hand.

**Comment by gskleres** [comment]
Added Ethereal.

**Comment by gskleres** [comment]
BUG: I'm getting a really weird bug ... whenever I spawn a copy of upgraded Siphon Magic+, it shows "Innate" when it's in my deck, but it loses Innate when the battle starts, and when I look through my draw pile, the card no longer says Innate nor does it have the "+" in its name. Any idea what's going on?

**Comment by gskleres** [comment]
Added some design changes. Card no longer Exhausts. Now adds 1 Artifact regardless. Regular card is also Innate, but upgrade costs 1 less.

When implementing please look at the bug in the above comment and change design to the one in the first comment, it's updated now.

**Comment by gskleres** [comment]
BUG: Upgraded version costs 3, should cost 1.

BUG: Cannot use "deck add Convergence" because it still uses the old name SiphonMagic. Update code to reflect new name.

**Comment by gskleres** [comment]
BUG: Should be castable even when there are no enemies with Artifact.

**Comment by gskleres** [comment]
BUG: When it transfers Artifact, it counts what's on the player as well, which essentially doubles it and then adds 1.

**Comment by gskleres** [comment]
Works!

**Comment by daviscook477** [comment]
Missing ethereal in description

**Comment by gskleres** [comment]
Dumped old card. New card is [Common Skill]: Unplayable. Ethereal. When you draw this card, upgrade a random(selected) card in your hand.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
BUG: Change-able numeric values in card text do not get updated when you use this mid combat. For example, if you upgrade Comet, the damage total it displays is still for the unupgraded version. If you use the card, it correctly deals the upgraded amount of damage, and the card text is properly updated when it is discarded (and from that point forward - redraw etc).

**Comment by gskleres** [comment]
Works!

**Comment by Butcherberries** [comment]
Minor text issue - When Convergence+ is activated, card text says "Choose a card to Select a card to upgrade."

**Comment by gskleres** [comment]
Design Update: No longer ethereal. Now both versions let you choose which card to upgrade, and upgraded version draws an extra card when you draw it.
