### ISSUE TITLE
Card 54 Siphon Speed

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#63]
Card 54

Name: Siphon Speed
Rarity: 2-Uncommon
Type: Skill
Basic [2 cost]: Gain 7 Block. Apply 1 Weak. Gain 1 Dexterity.
Upgrade [2 cost]: Gain 10 Block. Apply 2 Weak. Gain 1 Dexterity.

**Comment by gskleres** [comment]
No longer requires intent. Also adds Vulnerable now.

**Comment by dvalldejuli** [comment]
Added and Updated

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
DESIGN UPDATE: Dexterity gain reduced from 1(2) to 1(1). Block reduced from 7(9) to 5(8).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Apply Vulnerable changed to Apply Weak.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Updated. Block increased from 5(8) to 7(10).
