### ISSUE TITLE
Card 55 Stroke of Genius

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#64]
Card 55

Name: Stroke of Genius
Rarity: 2-Uncommon
Type: Skill
Basic [1 cost]: Add a random Power to your hand. Exhaust.
Upgrade [1 cost]: Add a random Power to your hand. It costs 0 this turn. Exhaust.

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug:
Got a friend to try the mod. His Stroke of Genius has the unlock icon instead of the appropriate art. He is using v0.3. Stroke of Genius doesn't appear to be an unlock card. Also the art is normal on mine, but I'm probably on a different version.

**Comment by gskleres** [comment]
Not reproduceable. Putting aside for now.
