### ISSUE TITLE
Card 57 Channel

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#66]
Card 57

Name: Channel
Rarity: 1-Common
Type: Attack
Basic [1 cost]: Deal 7 damage. Top-Cycle a card. Deal 7 more damage if it is Ethereal.
Upgrade [1 cost]: Deal 10 damage. Top-Cycle a card. Deal 10 more damage if it is Ethereal.

**Comment by gskleres** [comment]
Now has 7 base damage. Damage from discarding Ethereal reduced to 7.

**Comment by gskleres** [comment]
BUG: Upgraded version forces you to discard 2 cards instead of allowing you to discard 1 or 2.

**Comment by daviscook477** [comment]
Yeah I haven't implemented a nice way to do that yet. The card text is correct for the current behavior though

**Comment by gskleres** [comment]
Ok design updated to only ever use 1 card as a discard.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Rarity decreased from Rare to Common. Damage changed from 7(7) + 7(13) to 7(10) + 7(10).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Design update: No longer discards a card. Instead top-cycles the card. Still deals double damage if the selected card is Ethereal.
