### ISSUE TITLE
Card 58 Feedback

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#67]
Card 58

Name: Feedback
Rarity: 3-Rare
Type: Attack
Basic [1 cost]: Remove all Weak and Vulnerable from an enemy. That enemy loses 6 HP per stack removed.
Upgrade [1 cost]: Remove all Weak and Vulnerable from an enemy. That enemy loses 9 HP per stack removed.

**Comment by gskleres** [comment]
Damage per stack removed reduced from 8(12) to 6(9).

**Comment by dvalldejuli** [comment]
At the moment damage gets the vulnerability bonus to damage. Easy to change if needed.

**Comment by gskleres** [comment]
Should not get vuln boost to damage. Remove vuln/weak first, then apply damage.

**Comment by gskleres** [comment]
Still gets boost to damage if enemy is Vulnerable. Should remove Vulnerable (and Weak) first, then do damage for how much it removed. If this is impossible let me know and we can redesign! :)

**Comment by daviscook477** [comment]
Can't remove vulnerable first. Idea for change:
"Deal 5 damage to an enemy for each stack of Vulnerable it has. Remove all Vulnerable from that enemy"
On upgrade maybe 7 damage per.

**Comment by gskleres** [comment]
Let's leave it how it is for now. It's probably too strong but it won't be game breaking.

**Comment by gskleres** [comment]
Damage changed to HP loss to prevent scaling from both Strength and enemy Vulnerable. It should no longer benefit from either of those, but just be a straight 6(9) HP loss per stack.

**Comment by gskleres** [comment]
Works!
