### ISSUE TITLE
Card 60 Meteor Shower

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#69]
Card 60

Name: Meteor Shower
Rarity: 3-Rare
Type: Attack
Basic [1 cost]: Deal 1 damage to ALL enemies for each card in your draw pile. Exhaust.
Upgrade [1 cost]: Innate. Deal 1 damage to ALL enemies for each card in your draw pile. Exhaust.

**Comment by gskleres** [comment]
Now also Exhausts in both regular and upgraded versions.

**Comment by gskleres** [comment]
Card does not appear in game. Cannot add via the console, neither Regular or Upgraded.

**Comment by gskleres** [comment]
BUG 1: Neither regular nor upgraded version of this card does any damage. It shows correctly how much damage it SHOULD do on the card, but no damage is actually dealt to any enemies.

BUG 2: The text "NL" before the dynamic text of "(This will do X damage)" appears because it doesn't have a space before it.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
BUG: Rarity in game is Common, but should be Rare.

**Comment by daviscook477** [comment]
Rarity fixed
