### ISSUE TITLE
Card 62 Chaos Form

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#71]
Card 62

Name: Chaos Form
Rarity: 3-Rare
Type: Power
Basic [2 cost]: At the start of your turn, shuffle a random Ethereal card into your draw pile.
Upgrade [2 cost]: At the start of your turn, shuffle a random Ethereal card into your draw pile. It costs 0 until you play it.

**Comment by gskleres** [comment]
BUG: When casting this more than once, the first cast works correctly, but all future casts only add 1 to the stacks instead of 3(5).

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic): Rename in game name to Chaos Form.

**Comment by gskleres** [comment]
BUG: Chaos Form damage is affected by Weak. It should not be affected.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
BUG: Chaos Form power does not properly end after combat - it gets preserved into the next combat.

**Comment by gskleres** [comment]
Incorrect - the bug was happening because I was using cheat commands to go from one combat to the next without finishing.

**Comment by gskleres** [comment]
Complete card overhaul. New card is as follows:

At the start of your turn, shuffle a random Ethereal card into your draw pile. (It costs 0 until you play it.)

**Comment by gskleres** [comment]
BUG: Playing multiple Chaos Forms does not increase the number of cards generated. It should increase for each Chaos Form played. So for example, if you played 1 Chaos Form and 2 Chaos Form+, then you should get 3 Ethereal cards randomly generated, two of which cost 0 until they are played.

IMPROVEMENT: Please make Chaos Form trigger first before card draw. That way it will happen pre-shuffle and give you a chance to get those juicy Ethereals that cost 0 after upgrading Chaos Form.

**Comment by daviscook477** [comment]
Got the bug and the improvement

**Comment by gskleres** [comment]
BUG: Regular Chaos Form now triggers before card draw, but upgraded Chaos Form+ still does not trigger before card draw.

**Comment by gskleres** [comment]
Works!
