### ISSUE TITLE
Card 65 Event Horizon

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#74]
Card 65

Name: Event Horizon
Rarity: 2-Uncommon
Type: Power
Basic [1 cost]: Each enemy loses HP equal to the amount of Weak and Vulnerable it has at the start of its turn.
Upgrade [0 cost]: Each enemy loses HP equal to the amount of Weak and Vulnerable it has at the start of its turn.

**Comment by dvalldejuli** [comment]
Added and updated

**Comment by gskleres** [comment]
BUG: Power has no effect. Enemy does not lose HP for having Weak nor Vulnerable, regardless of whether regular or upgraded version of this card was cast (or even both).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
65 Event Horizon: Cost reduced from 2(1) to 1(0).

**Comment by gskleres** [comment]
Works!
