### ISSUE TITLE
Card 66 Runic Binding

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#75]
Card 66

Name: Runic Binding
Rarity: 2-Uncommon
Type: Power
Basic [2 cost]: Whenever you draw an Ethereal card, deal 3 damage to a random enemy.
Upgrade [2 cost]: Whenever you draw an Ethereal card, deal 5 damage to a random enemy.

**Comment by gskleres** [comment]
Rarity reduced from Rare to Uncommon. Cost reduced from 3(2) to 2(1). No longer grants Strength or Dexterity gain per turn. Regular version now grants 1 Artifact per turn just like upgraded version.

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug (Cosmetic):
The Tenacity buff still has the description of increasing str/dex.

**Comment by dvalldejuli** [comment]
Get latest? This seems to have been fixed at some point.

**Comment by gskleres** [comment]
BUG: The text in the pop up help box for status effects (hover over your own character) still says "At the start of your turn, gain X Strength and X Dexterity." Needs to be updated to the new +X Artifact effect.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Changed to old Chaos Form. Uncommon Power, cost is 2(2): Whenever you draw an Ethereal card, deal 3(5) damage to a random enemy.

**Comment by gskleres** [comment]
BUG: Card is still Rare. Should be Uncommon.

**Comment by gskleres** [comment]
Works!
