### ISSUE TITLE
Card 67 Nexus

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#76]
Card 67

Name: Nexus
Rarity: 3-Rare
Type: Power
Basic [2 cost]: Whenever you draw a non-Ethereal attack or skill, shuffle an Ethereal copy of it into your draw pile.
Upgrade [1 cost]: Whenever you draw a non-Ethereal attack or skill, shuffle an Ethereal copy of it into your draw pile.

**Comment by gskleres** [comment]
Need to redesign this entirely. Too many infinite combos possible too easily with just common cards in this set due to 1 cost cards that draw.

**Comment by gskleres** [comment]
Card removed ... reworked into entirely new card. Old card archived here:

Card 67

Name: Periapt of Vigor
Rarity: 3-Rare
Type: Power
Basic [3 cost]: Ethereal cards cost 1 less Energy.
Upgrade [2 cost]: Ethereal cards cost 1 less Energy.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
BUG: This effect lasts even after combat is over, so you start every other combat having it on.

**Comment by daviscook477** [comment]
Cannot reproduce

**Comment by gskleres** [comment]
Incorrect - the bug was happening because I was using cheat commands to go from one combat to the next without finishing.

**Comment by gskleres** [comment]
Cost reduced from 3(3) to 2(1). Effect changed to: Whenever you draw a non-Ethereal card, shuffle an Ethereal copy of it into your draw pile.

**Comment by daviscook477** [comment]
Currently we've got a visual bug where the ethereal cards that are added look like they aren't ethereal when shown to the user but the actual cards being added are.

**Comment by gskleres** [comment]
BUG (cosmetic): The power tooltip doesn't update the word "copy" when it has more than 1 copy shuffled, i.e. you played the card twice or more. It should update from "1 copy" to "2 copies" as more instances of Nexus are played.

DESIGN UPDATE: Whoops! This really really should not work on Powers, Status cards, or Curses... Card updated to specifically say "non-Ethereal attack or skill" to prevent that!

**Comment by gskleres** [comment]
BUG (cosmetic): The number of copies is never printed out. It only says "shuffle Ethereal copy" or "shuffle Ethereal copies" without specifying the amount.

**Comment by gskleres** [comment]
BUG: This draws Ethereal versions of cards that are previously generated from this power. Example: I draw a Flare, it makes an Ethereal version of Flare in my draw pile. Later, when I draw the Ethereal version of Flare, it makes an additional Ethereal version of Flare and adds it again. It should not create and add cards that are Ethereal, whether they are base Ethereal or created by this power Ethereal.

**Comment by gskleres** [comment]
Works!
