### ISSUE TITLE
Card 68 Dimension Door

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#77]
Card 68

Name: Dimension Door
Rarity: 3-Rare
Type: Skill
Basic [2 cost]: Ethereal. Gain 1 Intangible. Exhaust.
Upgrade [2 cost]: Ethereal. Gain 1 Intangible.

**Comment by gskleres** [comment]
BUG: Game crashes when adding Astral Shift+ via console.

**Comment by daviscook477** [comment]
AstralShift does not crash for me. I cannot reproduce the bug.

**Comment by daviscook477** [comment]
BUG: the intangible wears off before the enemy turn

**Comment by gskleres** [comment]
The crash only happens when adding the upgraded version of the card. The last output I had was as follows:

THE_SEEKER NOT FOUND IN CONFIRMPOPUP()01:34:37.267 [LWJGL Application] INFO  basemod.BaseMod - publish post combat
01:34:37.270 [LWJGL Application] INFO  com.megacrit.cardcrawl.monsters.AbstractMonster - Disposing Atlas...
01:34:38.281 [LWJGL Application] INFO  com.megacrit.cardcrawl.rooms.AbstractRoom - MONSTERS SLAIN 1
01:34:38.284 [LWJGL Application] INFO  com.megacrit.cardcrawl.rooms.AbstractRoom - POTION CHANCE: 40
01:34:38.286 [LWJGL Application] INFO  com.megacrit.cardcrawl.cards.AbstractCard - ERROR: Card color was NOT set for Flux Bolt
01:34:38.288 [LWJGL Application] INFO  basemod.BaseMod - successfully set properties for fruitymod.cards.FluxBolt with color PURPLE
01:34:38.298 [LWJGL Application] INFO  com.megacrit.cardcrawl.cards.AbstractCard - ERROR: Card color was NOT set for Void Barrier
01:34:38.299 [LWJGL Application] INFO  basemod.BaseMod - successfully set properties for fruitymod.cards.VoidBarrier with color PURPLE
01:34:38.305 [LWJGL Application] INFO  com.megacrit.cardcrawl.cards.AbstractCard - ERROR: Card color was NOT set for Hypothesis
01:34:38.306 [LWJGL Application] INFO  basemod.BaseMod - successfully set properties for fruitymod.cards.Hypothesis with color PURPLE
01:34:38.311 [LWJGL Application] INFO  com.megacrit.cardcrawl.screens.saveAndContinue.SaveFile - Next Room: com.megacrit.cardcrawl.rooms.MonsterRoom
01:34:38.339 [LWJGL Application] INFO  com.megacrit.cardcrawl.helpers.FileSaver - Save Succeeded: saves\THE_SEEKER.autosave
01:34:44.600 [LWJGL Application] INFO  com.megacrit.cardcrawl.cards.AbstractCard - ERROR: Card color was NOT set for Astral Shift
01:34:44.602 [LWJGL Application] INFO  basemod.BaseMod - successfully set properties for fruitymod.cards.AstralShift with color PURPLE

**Comment by gskleres** [comment]
BUG: When playing multiple Astral Shifts, the first one works correctly, but upon casting the 2nd one it then removes the little "1" next to the astral shift buff icon and proceeds to only give you 1 turn regardless.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
BUG: This internal ID is still labeled as "Astral Shift"

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Updated: Cost reduced from 3(3) to 2(2).
