### ISSUE TITLE
Card 70 Eclipse

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#79]
Card 70

Name: Eclipse
Rarity: 3-Rare
Type: Skill
Basic [1 cost]: Choose an Exhausted Ethereal card. Put it on top of your draw pile. Exhaust.
Upgrade [0 cost]: Choose an Exhausted Ethereal card. Put it on top of your draw pile. Exhaust.

**Comment by gskleres** [comment]
Slight rewording of this card, plus adding Exhaust. Current stuff is above in first comment. Here's what it was:

Basic [2 cost]: Ethereal. Choose an Exhausted Ethereal card. Play a 0-cost copy of it.
Upgrade [1 cost]: Ethereal. Choose an Exhausted Ethereal card. Play a 0-cost copy of it.

**Comment by dvalldejuli** [comment]
card is set to target an enemy to start this is because if an exhausted attack card is selected it needs to be supplied with a target. The other option is to give them the card to play.

**Comment by daviscook477** [comment]
Since targetting an enemy is awkward let's go ahead and just make it target self and then allow the player to select an exhausted card and put a-cost copy of it into their hand.

Maybe word it like: "Basic [2 cost]: Ethereal. Choose an Exhausted Ethereal card. Place a 0-cost copy of it into your hand."

**Comment by gskleres** [comment]
Since we need to put the card in hand, I updated the design so that it wasn't an exact duplicate of Exhume, but just for Ethereal. It now makes the cost of that Ethereal card 0 for this turn and adds Exhaust to the card.

**Comment by dvalldejuli** [comment]
Updated card

**Comment by gskleres** [comment]
BUG: I had 2 Void Barriers in my exhausted card pile (those are Ethereal cards) and when I tried to play either Eclipse or Eclipse+, it said I had no Exhausted Ethereal cards.

**Comment by gskleres** [comment]
Works!
