### ISSUE TITLE
Card 72 Nova

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#81]
Card 72

Name: Nova
Rarity: 2-Uncommon
Type: Attack
Basic [3 cost]: Deal 24 damage to ALL enemies.
Upgrade [2 cost]: Deal 24 damage to ALL enemies.

**Comment by daviscook477** [comment]
Very similar in function to Astral Shift. Possibly could use a rework. Also implementing stuns would be nearly impossible so let's not.

**Comment by gskleres** [comment]
Since stunning is not possible, card has been reworked to be a sort of AoE version of Implosion.

**Comment by Paltorz** [comment]
Bug:
No retaliation from spikers, even though it shows up as an atk.

**Comment by gskleres** [comment]
Punting the spiker bug for now. Not important enough to get v0.1 out.

**Comment by gskleres** [comment]
Cost reduced from 3(3) to 3(2). Rarity reduced from Rare to Uncommon. Damage changed from 20(30) to 24(24).

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
No longer shuffles any Dazed.

**Comment by gskleres** [comment]
Done.
