### ISSUE TITLE
Card 73 Reflection Ward

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#82]
Card 73

Name: Reflection Ward
Rarity: 3-Rare
Type: Skill
Basic [2 cost]: Gain 4 Block and 2 Reflect per 4 cards in your draw pile.
Upgrade [2 cost]: Gain 4 Block and 2 Reflect per 3 cards in your draw pile.

NOTE: Reflect needs to be a yellow keyword that has the tooltip "Whenever you are attacked this turn, deal this amount of damage back to the attacker." The keyword should have an icon under the character with the current stacks of Reflect (just use thorns/caltrops icon for now).

EXAMPLE: If this keyword had existed previously, Flame Barrier would be written "Gain 12 Block and 4 Reflect." It's upgrade would be "Gain 16 Block and 6 Reflect."

**Comment by gskleres** [comment]
Damage reduced from 7(10) to 4(6). Now also grants 8(11) Block.

**Comment by dvalldejuli** [comment]
Added and updated

**Comment by gskleres** [comment]
BUG: Does not give any block (though the card text does correctly say it should).
EXPECTED: Card should give 8(11) Block on use.

**Comment by gskleres** [comment]
Works!

**Comment by gskleres** [comment]
Card effect changed to "Gain 4 Block and 2 Reflect per 4(3) cards in your draw pile." and new Reflect keyword added.

**Comment by gskleres** [comment]
**BUG**: Dexterity applies to each individual gain of 4 Block. Should only apply to the total gain.

Reflection Ward: 
* BlockGained = (4 * NumCardsInDrawPile / 4) + Dexterity
* ReflectGained = (2 * NumCardsInDrawPile / 4)

Reflection Ward+: 
* BlockGained = (4 * NumCardsInDrawPile / 3) + Dexterity
* ReflectGained = (2 * NumCardsInDrawPile / 3)

(I know the basic card formula is redundant with 4 * and / 4 but that number might change)

**IMPROVEMENT** (Cosmetic): It would be much nicer if it showed both the total block and reflect in parenthesis. For example, if it would apply 3 times and you have 2 Dexterity, it would say: "(Will gain 14 Block and 6 Reflect)"

**Comment by gskleres** [comment]
BUG (cosmetic): In the parenthesis summary text at the bottom, the word Reflect is not highlighted in yellow. Additionally, if the Block is increased by Dexterity, the number stays white instead of turning Green like it does with regular card text.

**Comment by gskleres** [comment]
Works!
