### ISSUE TITLE
Card 74 Zenith

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#83]
Card 74

Name: Zenith
Rarity: 3-Rare
Type: Skill
Basic [1 cost]: Double your Energy. Exhaust.
Upgrade [1 cost]: Double your Energy.

**Comment by gskleres** [comment]
BUG 1: Currently doubles then removes 1 energy. Should cost the energy first and then double. If this is impossible, then I will change the card to be 0 cost: Lose 1 Energy. Then double your remaining Energy.

BUG 2: Upgraded description says "null"

**Comment by daviscook477** [comment]
Well it looks like the card cost *will* be applied after use. I could make it give the player double their energy -1 so when the card cost of 1 is applied it evens out the (energy - 1) * 2

**Comment by gskleres** [comment]
That's perfect! As long as it doesn't crash or mess up showing -2 energy when the player's energy is at 0 and casts it lol...

**Comment by gskleres** [comment]
Works!

**Comment by Paltorz** [comment]
Bug:
Currently broken with changed cost, namely Sneko. 
Mana at time of cast: 4
Cost at time of cast: 3
Card's description of mana after cast: 6
Actual mana after cast: 4

**Comment by dvalldejuli** [comment]
fixed

**Comment by gskleres** [comment]
BUG: Card text on upgrade was not clarified. I did that and committed - will be in next build.

**Comment by gskleres** [comment]
Works!
