### ISSUE TITLE
Character Select Art

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#87]
Use this: https://drive.google.com/open?id=18tr3QNzeV_G_3xGcH2T7pbEwgWGEC1zD

**Comment by daviscook477** [comment]
Eventually we may want to try and improve the character select art so it fits with the game style but I'm not sure how feasible that is.

**Comment by Jrawly2** [comment]
@daviscook477 oh it's feasible. We gon' do it!
