### ISSUE TITLE
In-Game Avatar

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#88]
Use Ironclad avatar, recolor to something purple-ish

**Comment by daviscook477** [comment]
We have the tech necessary to implement a custom avatar but the time required to add in a new character/enemy asset is definitely a lot of work b/c it requires creating a spirte atlas of all of their parts, rigging them up as a skeleton and adding animations

**Comment by JEnglish-ETG** [comment]
^ Working on this. Should have a character design/skeleton within the week.
