### ISSUE TITLE
Arcanosphere Select Text

### ISSUE THREAD

**Issue by daviscook477** [gskleres/FruityMod-StS#90]
Currently it says to "Select a Card to Retain" so we should change that

**Comment by gskleres** [comment]
We have 2 choices here:

(1) Change text to "Select a Card to place on top of your draw pile."

(2) Create a new yellow keyword called Recycle, which has the defined text of "Recycle: When you Recycle a card, put it on top of your draw pile."

**Comment by fiiiiilth** [comment]
I changed the Select Text to option 1 for now. If/when we implement a "Recycle" mechanic/keyword, it can easily be changed.

**Comment by gskleres** [comment]
@fiiiiilth fixed this. closing it out! it works!
