### ISSUE TITLE
Inconsistent card IDs

### ISSUE THREAD

**Issue by gskleres** [gskleres/FruityMod-StS#92]
Stroke of Genius is "StrokeOfGenius" with the Of uppercase camel case.

All others so far (ex: Periapt of Celerity) have the Of lowercase (ex: "PeriaptofCelerity").

We should choose one and be consistent. I'm ok with changing the name of the cards displayed to have upper or lower case - doesn't matter to me. You two decide what you want in the code.

**Comment by daviscook477** [comment]
My preference is Upper Camel Case

**Comment by dvalldejuli** [comment]
me too

**Comment by gskleres** [comment]
@dvalldejuli @daviscook477 Ok, then it's decided. Internally all card IDs should be upper camel cased (ex: "PeriaptOfCelerity") but on the display names of cards minor prepositions will still be lower case to preserve consistency with existing cards (ex: "Periapt of Celerity").

I'll come up with a list of the IDs / Display names that don't follow this rule and post it on this issue as a bug.
