### ISSUE TITLE
Umbral Wave Bug

### ISSUE THREAD

**Issue by Paltorz** [gskleres/FruityMod-StS#99]
Umbral Wave+ not triggering thorns damage from the guardian. Unsure of interaction with spikers or unupgraded Umbral Wave.

**Comment by Paltorz** [comment]
Additional issue. Unupgraded Umbral Wave gives -1 energy the following turn, instead of +1. But only if used on the first turn of combat. Idk how that happened.

**Comment by gskleres** [comment]
Closing this and using base card issue instead.
